### ISSUE TITLE
[C1S11] As a gamer I should be able to get prizes

### ISSUE THREAD

**Issue by adamggg** [MGhanem/smartsoft-13#164]
_Success:_ 
While I'm playing the game if i acomplish certain tasks a pop-up windows appears with the prize that i won and a detailed description of that prize

_Failure:_
If i am not signed in i cannot win anything since guests cant win prizes, or if i am not playing the game

Scenario Reviewer: @KareemAliRahman 
Implementation Reviewer: @NourhanMohamed 
UML Reviewer: @Khloud-Khalid 
Documentation Reviewer: @zoheiry

**Comment by Khloud-Khalid** [comment]
UML verified.

**Comment by zoheiry** [comment]
All tests verified

**Comment by NourhanMohamed** [comment]
games_controller.rb line 115, method should be renamed to get_prizes according to conventions
this is as well as showprizes and showtrophies that should be renamed, too

**Comment by krmali** [comment]
@adamggg , scenario verified

**Comment by NourhanMohamed** [comment]
fix showprizes method name

**Comment by NourhanMohamed** [comment]
code verified

**Comment by NourhanMohamed** [comment]
@adamggg close the issue, it's merged now
