### ISSUE TITLE
[C1S12] As a gamer I should be able to get trophies

### ISSUE THREAD

**Issue by adamggg** [MGhanem/smartsoft-13#165]
_Success:_
While I'm playing the game if i acomplish certain tasks a pop-up windows appears with the trophy that i won

_Failure:_
if i am not signed in i cannot win anything since guests cant win trophies, or if i am not playing the game

Scenario Reviewer: @KareemAliRahman
Implementation Reviewer: @NourhanMohamed 
UML Reviewer: @Khloud-Khalid
Documentation Reviewer: @zoheiry

**Comment by zoheiry** [comment]
Docs all good

**Comment by Khloud-Khalid** [comment]
UML verified.

**Comment by zoheiry** [comment]
tests good. Verified

**Comment by NourhanMohamed** [comment]
check pull request comments

**Comment by NourhanMohamed** [comment]
fix showtrophies method name and be sure there is only one method not a duplicate

**Comment by NourhanMohamed** [comment]
code verified

**Comment by krmali** [comment]
scenario verified

**Comment by krmali** [comment]
@adamggg , solve conflicts
