### ISSUE TITLE
C1S2 - A gamer/guest I should be able to form a word  

### ISSUE THREAD

**Issue by zoheiry** [MGhanem/smartsoft-13#166]
Success: after forming all the words in the databse, i should still be able to keep playing the game but without voting
Failure: no failure

Tasks:

1- Sequence Diagram @Khloud-Khalid 
2- Documentation @mostafahassaan 
3- Research
4- Implementation @adamggg 
5- Testing @KareemAliRahman

**Comment by krmali** [comment]
review the comment on the pull request.

**Comment by adamggg** [comment]
@zoheiry check out my comments ASAP =)

**Comment by krmali** [comment]
Scenario verified

**Comment by Khloud-Khalid** [comment]
@zoheiry the 'checks if there are words in the database' arrow should be outside the box since it's the condition.
also, the unvoted_keywords model should not keep running after it returns its responses (false the first time then the array of words the second time)

**Comment by zoheiry** [comment]
@Khloud-Khalid  Fixed, please Review

**Comment by Khloud-Khalid** [comment]
verified

**Comment by mostafahassaan** [comment]
will check tests tomorrow with you, i don't know how to test jasmin

**Comment by mostafahassaan** [comment]
docs verified

**Comment by zoheiry** [comment]
just run "rake jasmine", then go to localhost:8888

**Comment by mostafahassaan** [comment]
verified tests
