### ISSUE TITLE
C4-S03 As a Developer, I can view the collective visuals/stats about the keyword synonyms

### ISSUE THREAD

**Issue by mostafahassaan** [MGhanem/smartsoft-13#168]
_Success:_
Get a pie chart showing the percentage of  division of votes between synonym of the keyword.
_Failure:_
No synonyms found. Suggest following keyword. A developer may have exhausted his search quota or if this feature is not allowed for subscription model of the developer by the admin.

Documentation: @zoheiry 
SD: @nourhanZ 
Implementation: @NourhanMohamed 
Scenario: @m0hamed

**Comment by NourhanMohamed** [comment]
apply comments of #177

**Comment by nourhanZ** [comment]
1) please review the structure of the code as the UML seems to be ambiguous and tag me again

**Comment by mostafahassaan** [comment]
@NourhanMohamed please review

**Comment by mostafahassaan** [comment]
@nourhanZ fixed UML

**Comment by m0hamed** [comment]
Scenario verified.

**Comment by m0hamed** [comment]
Scenario verified.
