### ISSUE TITLE
[ C1S27 ] As guest/gamer I should be able to select a synonym

### ISSUE THREAD

**Issue by krmali** [MGhanem/smartsoft-13#169]
Success:
clicks on the available choices for the current term that needs to be translated, after i click a new term appears if there are any.

Failure:
No failure.

Scenario Reviewer: @m0hamed 
Implementation Reviewer: @adamggg 
UML Reviewer: @Khloud-Khalid
Documentation Reviewer: @zoheiry

**Comment by ghost** [comment]
@KareemAliRahman  please fix the labels for this issue

**Comment by m0hamed** [comment]
please pull master this branch is too old and remove that useless start voting link

**Comment by krmali** [comment]
@m0hamed  these branches with their pull requests are closed now and there is one branch with the whole vote form functionality

**Comment by m0hamed** [comment]
the popover that appears when I try to vote for a word asking me for formality cannot be closed even when I click the close button or vote for another synonym

**Comment by krmali** [comment]
@m0hamed, we agreed that when a gamer adds a new synonym, he must specify the formality , but when he vote for a synonym we don't need to force him , he cannot vote on this synonym (given that the synonym has is_formal =nil ) unless he/she specify the formality , but he can choose not to vote and choose another synonym or maybe skip the this vote, we agreed upon this.

**Comment by m0hamed** [comment]
You dont seem to understand me. It cannot close even after I vote. There is something wrong with the javascript  

## 

Mohamed Ashraf
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by m0hamed** [comment]
so will you change this or what. the popover doesnt close.

**Comment by m0hamed** [comment]
ok so it sometimes works and sometimes not.

**Comment by m0hamed** [comment]
I chose a word and the popup appeared. I pressed one of the buttons but the popup didnt disappear untill I refreshed the page. Another time I did it and it worked I still dont know why

**Comment by Khloud-Khalid** [comment]
UML verified.

**Comment by krmali** [comment]
@adamggg , @m0hamed , @Khloud-Khalid , please review

**Comment by adamggg** [comment]
@KareemAliRahman code verified =)

**Comment by m0hamed** [comment]
verified

**Comment by Khloud-Khalid** [comment]
UML verified.
