### ISSUE TITLE
[ C1S25 ] As guest/gamer I should be able to suggest my own synonym to a keyword

### ISSUE THREAD

**Issue by krmali** [MGhanem/smartsoft-13#170]
Success:
Writes suggestion presses enter or clicks submit, another term appears. if two or more gamers have added the same synonym then send notification to all the developers following the word.

Failure:
Write nothing, he will remain on current term.
Scenario Reviewer: @m0hamed  
Implementation Reviewer: @adamggg 
UML Reviewer: @Khloud-Khalid
Documentation Reviewer: @zoheiry

**Comment by Khloud-Khalid** [comment]
@KareemAliRahman  
the actor's interactions with the view should be indicated by an arrow from the actor's lifeline to the view.
why does the controller keep working after it calls the suggest_synonym method?
arrows that return responses/parameters should be dashed

**Comment by ghost** [comment]
@KareemAliRahman please fix the labels for this issue

**Comment by m0hamed** [comment]
where is the pull request

**Comment by m0hamed** [comment]
where is the pull request

**Comment by Khloud-Khalid** [comment]
UML verified.

**Comment by zoheiry** [comment]
Docs looking good, verified

**Comment by krmali** [comment]
@adamggg , @m0hamed , please review

**Comment by adamggg** [comment]
@KareemAliRahman code verified =)

**Comment by m0hamed** [comment]
verified
