### ISSUE TITLE
[C1S14] As a gamer I should be able to view and know how to get trophies

### ISSUE THREAD

**Issue by adamggg** [MGhanem/smartsoft-13#171]
_Success:_
After i click on the trophies button i am redirected to the trophies page which displays the trophies that i have earned and the ones which are yet to be earned, and a detailed description on how to earn those trophies which i have not earned yet.

_Failure:_
I am not logged in, or i have already earned a specific trophy, therefore the trophy that i have earned will be highlighted with a different color, and no description available for it since i have already earned it

Scenario Reviewer: @KareemAliRahman 
Implementation Reviewer: @Omar-Hossam 
UML Reviewer: @Khloud-Khalid
Documentation Reviewer: @zoheiry

**Comment by Khloud-Khalid** [comment]
UML verified.

**Comment by zoheiry** [comment]
tests looking good here as well. Verified

**Comment by NourhanMohamed** [comment]
almost verified, check pull request comment

**Comment by NourhanMohamed** [comment]
code verified

**Comment by krmali** [comment]
scenario verified
