### ISSUE TITLE
C4-S08 As a Developer, I can follow words

### ISSUE THREAD

**Issue by mostafahassaan** [MGhanem/smartsoft-13#172]
_Success:_
Choose a keyword to follow. if that keyword gets a new synonym by two different gamers send a notification email to developer
_Failure:_
If the developer is already following the word, the button will be shown as "un follow word".And also if Admin decides to limit to certain subscriptions

Documentation: @zoheiry 
SD: @nourhanZ 
Implementation: @NourhanMohamed 
Scenario: @m0hamed

**Comment by nourhanZ** [comment]
Hassan please make the boxes representing each method starts directly when arrow is calling not before and
make the whole box of the second if inside the first if part not else included and end the life line of the user with x

**Comment by nourhanZ** [comment]
1) please add the return type after each method 
2) return true of the flash is not correctly placed on the return line please fix it
3) the activation box must not start before the line that calls the method and must not remain after the last return line of the method

**Comment by mostafahassaan** [comment]
@NourhanMohamed please review

**Comment by mostafahassaan** [comment]
@nourhanZ please review

**Comment by mostafahassaan** [comment]
@nourhanZ fixed uml

**Comment by mostafahassaan** [comment]
Since story C4S08 and C4S09 have been merge please just add your comments here. Both stories will still be refrenced during commit.

**Comment by mostafahassaan** [comment]
please review :)

**Comment by m0hamed** [comment]
I cant acces you page because someone approved non working code

**Comment by zoheiry** [comment]
Good Job, Reviewed

**Comment by mostafahassaan** [comment]
@m0hamed @NourhanMohamed @nourhanZ please review again

**Comment by m0hamed** [comment]
verified

**Comment by NourhanMohamed** [comment]
check the pull request comments

**Comment by nourhanZ** [comment]
verified :)

**Comment by NourhanMohamed** [comment]
see pull request comments

**Comment by NourhanMohamed** [comment]
code verified (Y)

**Comment by mostafahassaan** [comment]
@m0hamed @NourhanMohamed please review

**Comment by NourhanMohamed** [comment]
code verified

**Comment by m0hamed** [comment]
mostafa you opened a script and forgot to close it. the button is not visible and the javascript shows an exception

**Comment by mostafahassaan** [comment]
fixed, sorry about that :)

**Comment by m0hamed** [comment]
verified
