### ISSUE TITLE
[C1S13] As a gamer I should be able to view and know how to get prizes

### ISSUE THREAD

**Issue by adamggg** [MGhanem/smartsoft-13#174]
_Success:_
After i click on the prizes button i am redirected to the prizes page which displays the prizes that i have earned and the ones which are yet to be earned, and a detailed description on how to earn those prizes which i have not earned yet.

_Failure:_
I am not logged in, or i have already earned a specific prize, therfore the prize that i have earned will be highlighted with a different color, and no description available for it since i have already earned it

Scenario Reviewer: @KareemAliRahman
Implementation Reviewer: @NourhanMohamed 
UML Reviewer: @Khloud-Khalid
Documentation Reviewer: @zoheiry

**Comment by zoheiry** [comment]
All tests are a Go! Verified

**Comment by Khloud-Khalid** [comment]
UML verified.

**Comment by NourhanMohamed** [comment]
almost verified.. just a single comment on the pull request :)

**Comment by NourhanMohamed** [comment]
code verified

**Comment by krmali** [comment]
scenario verified
