### ISSUE TITLE
C4-S09 As a Developer, I can un-follow words

### ISSUE THREAD

**Issue by mostafahassaan** [MGhanem/smartsoft-13#175]
_Success:_
the developer will not get  notification emails about the updates of this word anymore and the button will show "follow word" again 
_Failure:_
If the developer is not following the word he/she can't unfollow it as the button will be showing "follow word"

Documentation: @zoheiry 
Implementation: @NourhanMohamed 
SD: @nourhanZ 
Scenario: @m0hamed

**Comment by nourhanZ** [comment]
please the variable names on the UML must be the same as the code and show me the flow don't check on a variable without showing from where did you get this variable

**Comment by NourhanMohamed** [comment]
apply same comments as #177

**Comment by mostafahassaan** [comment]
@NourhanMohamed please review

**Comment by mostafahassaan** [comment]
@nourhanZ fixed uml

**Comment by mostafahassaan** [comment]
This story has been merged with story C4S08, Issue #172. The issue had been closed, so I'm closing this one too.
