### ISSUE TITLE
[ C1S24 ] As a guest/gamer I should be able to skip certain terms

### ISSUE THREAD

**Issue by krmali** [MGhanem/smartsoft-13#176]
Success:
Click skip button and another term appears.

Failure:
No Failure.

Scenario Reviewer: @m0hamed 
Implementation Reviewer: @adamggg 
UML Reviewer: @Khloud-Khalid
Documentation Reviewer: @zoheiry

**Comment by ghost** [comment]
@KareemAliRahman  please fix the labels for this issue

**Comment by m0hamed** [comment]
please pull master because this is very old and alot of things have changed

**Comment by m0hamed** [comment]
verified

**Comment by Khloud-Khalid** [comment]
@KareemAliRahman the activation box of the vote view should be continous.

**Comment by Khloud-Khalid** [comment]
UML verified.

**Comment by krmali** [comment]
@adamggg, review

**Comment by zoheiry** [comment]
Docs, Verified all good

**Comment by krmali** [comment]
@adamggg , please review

**Comment by adamggg** [comment]
@KareemAliRahman code verified =)
