### ISSUE TITLE
C4-S10 As a Developer, I can list the words followed by me

### ISSUE THREAD

**Issue by mostafahassaan** [MGhanem/smartsoft-13#177]
_Success:_
the developer get a list of followed words with "un follow word" button beside each. 
_Failure:_
if the developer is not following any word yet --> You're not following any words yet

Documentation: @zoheiry 
SD: @nourhanZ 
Implementation: @NourhanMohamed 
Scenario: @m0hamed

**Comment by mostafahassaan** [comment]
@zoheiry @m0hamed @NourhanMohamed @nourhanZ please review

**Comment by mostafahassaan** [comment]
issue #177

**Comment by nourhanZ** [comment]
1) the activation box should start when the line call the method not before.
2) add the return type after each method
3) there's a return line without anything returned on it please fix this
4) after you get the listed keywords array @Keyword you first check it it's not empty so please add this part to the UML

**Comment by NourhanMohamed** [comment]
check pull request comments

**Comment by mostafahassaan** [comment]
@NourhanMohamed please review

**Comment by mostafahassaan** [comment]
@nourhanZ fixed UML

**Comment by NourhanMohamed** [comment]
finish these and U'll be verified

**Comment by m0hamed** [comment]
where is the pull requst for this issue. I cant verify if I dont have a pull request

**Comment by mostafahassaan** [comment]
@m0hamed @nourhanZ @NourhanMohamed @zoheiry review please :)

**Comment by NourhanMohamed** [comment]
code verified

**Comment by m0hamed** [comment]
the text should be changed to "إتبع كلمات لتلقي بريد إلكتروني بمعلومات جديدة عن كلماتك. سيصلك بريد إن حصلت كلمة على مرادفات جديدة" only and should be visible even if there are no followed words. same for English since we only send new synonyms

**Comment by mostafahassaan** [comment]
done. Pleasr review @m0hamed

**Comment by nourhanZ** [comment]
UML verified

**Comment by m0hamed** [comment]
please tell the user how to follow a word which is to search for it and and click follow

**Comment by mostafahassaan** [comment]
review please @m0hamed

**Comment by mostafahassaan** [comment]
@m0hamed review please

**Comment by m0hamed** [comment]
open pull request please @mostafahassaan

**Comment by m0hamed** [comment]
verified
