### ISSUE TITLE
C1S16 - KarimElNaggar - As an admin i should be able to add prizes

### ISSUE THREAD

**Issue by ghost** [MGhanem/smartsoft-13#182]
Success: Click on a button that redirects to the prizes page with an add button that redirects to the add form where i enter the prize name, photo, and information on how to get that prize.

Failure: Not an admin, wont have the add button, or i have left one of the fields empty and tried to add, thefore the page will be reloaded and the fields where the error occured are highlighted.

Tasks:

C1S16.0 - Writing unit tests - Reviewer: @m0hamed 
C1S16.1 - Designing UML sequence diagram - Reviewer: @Mirna-Yacout 
C1S16.2 - Implementing the add prize procedure - Reviewer: @Omar-Hossam 
C1S16.3 - Documenting the add prize procedure - Reviewer: @AmrARaouf 
C1S16.4 - Writing the user interface for adding a prize - Reviewer: @Omar-Hossam 
C1S16.5 - Styling the user interface for adding a prize - Reviewer: @Omar-Hossam

**Comment by m0hamed** [comment]
verified
