### ISSUE TITLE
C2S04 - As a gamer, I could tweet my score through twitter

### ISSUE THREAD

**Issue by omar-mohyeldin** [MGhanem/smartsoft-13#185]
success: tweeted on twitter confirmed by API
failuer: twitter failure reported by API
Tasks:
Research how to use twitter API to implement function
implement story using rails @nohahesham 
UI
testing @karimngr 
UML @Mirna-Yacout 
Documentation @AmrARaouf

**Comment by Mirna-Yacout** [comment]
ok UML reviewed then
