### ISSUE TITLE
C3.S22 As a developer, I should be able to import data in csv and add it to a project and Database

### ISSUE THREAD

**Issue by abulazm22** [MGhanem/smartsoft-13#186]
Success:From the project, the developer can import a .csv file. Words and their meanings will be added to the current project. Repititions will be handled through asking the user to choose the desired meanings. All keywords added to the project should take the category of the project if not already assigned.
Failure: none
1)Research 
2)UML @Mirna-Yacout 
3)Implement @nohahesham 
4)Test @m0hamed 
5)Documentation @SalmaFG

**Comment by m0hamed** [comment]
"Tou can change the synonym later" is written in the instructions

**Comment by m0hamed** [comment]
if a keyword or a synonym is present multiple times it is visible multiple times. it should only be visible once and should be combined into one row showing all the synonyms

**Comment by m0hamed** [comment]
this is not fixed are you sure you fixed it. I get the same keyword listed multliple times

**Comment by abulazm22** [comment]
Yes. it is working here please make sure you pulled latest branch

**Comment by m0hamed** [comment]
verified
