### ISSUE TITLE
C3.S21: As a Developer I Should be able to export my data.

### ISSUE THREAD

**Issue by Khloud-Khalid** [MGhanem/smartsoft-13#188]
Success: Words and their meanings/alternatives will be exported in a csv, xml, or json file.

Failure: no words in project.

UML @nourhanZ 
Scenario @KareemAliRahman 
Implementation @adamggg 
Documentation+Testing @zoheiry

**Comment by nourhanZ** [comment]
1) Fix the line of the gamer add actor box
2) the part of retrieving synonyms in CSV should be in a loop box
3) change the click notation to click[button name]

**Comment by Khloud-Khalid** [comment]
@nourhanZ  done

**Comment by adamggg** [comment]
@Khloud-Khalid Code has been reopened =)

**Comment by Khloud-Khalid** [comment]
@adamggg , @zoheiry please review tests and code

**Comment by zoheiry** [comment]
I have commented on your documentation, please take a look at it, and as for the tests... you have 6 passing tests, and 1 failure 
Failures:

  1) ProjectsController a developer can open the link of import of one of his projects
     Failure/Error: sign_in developer1.gamer
     RuntimeError:
       Could not find a valid mapping for nil
     # ./projects_controller_spec.rb:55:in `block (2 levels) in <top (required)>'

**Comment by krmali** [comment]
check the scenario comments on the pull request.

**Comment by Khloud-Khalid** [comment]
@zoheiry  the test that fails is not mine the importing projects action is timo's

**Comment by zoheiry** [comment]
which test file should i be running?

**Comment by Khloud-Khalid** [comment]
@zoheiry the test you're running is correct..the one for the projects_controller.However, it includes one test case that's not mine since there's more than one person working in the projects_controller. You'll find that i wrote my name before my test cases though.

**Comment by Khloud-Khalid** [comment]
@zoheiry , @KareemAliRahman done.

**Comment by zoheiry** [comment]
Looks like you're good to go, Docs, and tests verifed

**Comment by krmali** [comment]
Scenario verified

**Comment by adamggg** [comment]
@Khloud-Khalid check the comments I have left on the files =)
Code reopened.

**Comment by adamggg** [comment]
@Khloud-Khalid and does this story belong to sprint 1 or 2? if 2 please do change its milestone label

**Comment by Khloud-Khalid** [comment]
@adamggg please review now. =)

**Comment by adamggg** [comment]
@Khloud-Khalid check my comments and code has been reopened =)

**Comment by adamggg** [comment]
@Khloud-Khalid code veri.

**Comment by nourhanZ** [comment]
everything is fine except that you need to add a small box when writing whether in the xml of json or csv to indicate that you're not calling the same method you're currently in :)

**Comment by Khloud-Khalid** [comment]
@nourhanZ fixed. :)

**Comment by nourhanZ** [comment]
Sorry but I have just another comment please make the activation box of the view end when the view calls the controller and another activation box start when the controller return the written file to the view again.
Sorry but I just noticed that now :)

**Comment by Khloud-Khalid** [comment]
@nourhanZ done.

**Comment by nourhanZ** [comment]
verified :)

**Comment by Khloud-Khalid** [comment]
@nourhanZ please merge since you're the last reviewer to verify =)
