### ISSUE TITLE
C5F1, I should be able to send automated E-mails to any email address

### ISSUE THREAD

**Issue by m0hamed** [MGhanem/smartsoft-13#189]
success I will send the email to the specified address
failure: wrong format for address or api unaccessible

documentation: @mostafahassaan 
implementation: @NourhanMohamed 
uml: @nourhanZ 
scenario: @KareemAliRahman

**Comment by m0hamed** [comment]
please review

**Comment by NourhanMohamed** [comment]
check the pull request comments

**Comment by mostafahassaan** [comment]
All docs should be with this template, check missing parts
 author:
      Amr Abdelraouf
 description:
     function description
 params:
     parameters
 success:
     success scenario
 failure:
     failure scenario

**Comment by nourhanZ** [comment]
1) Change the title of the sequence diagram
2) indicate that each one represent a different scenario

**Comment by m0hamed** [comment]
please review

**Comment by NourhanMohamed** [comment]
check pull request comments

**Comment by m0hamed** [comment]
please review

**Comment by NourhanMohamed** [comment]
reviewed, see comments on pull request
you also have a comment in line 37 in file user_mailer_spec.rb, either delete it or uncomment it

**Comment by m0hamed** [comment]
please review again

**Comment by NourhanMohamed** [comment]
code verified

**Comment by nourhanZ** [comment]
UML verified :)

**Comment by krmali** [comment]
Scenario verified

**Comment by m0hamed** [comment]
@mostafahassaan please verify

**Comment by m0hamed** [comment]
@mostafahassaan please review after fixing some tests

**Comment by m0hamed** [comment]
@mostafahassaan review here

**Comment by mostafahassaan** [comment]
tests verified

**Comment by mostafahassaan** [comment]
check comments on docs

**Comment by m0hamed** [comment]
@mostafahassaan please review and merge

**Comment by mostafahassaan** [comment]
docs verified

**Comment by mostafahassaan** [comment]
merged :)
