### ISSUE TITLE
C2S06 - As a gamer, I could tweet an invitation link to the Arability website game

### ISSUE THREAD

**Issue by omar-mohyeldin** [MGhanem/smartsoft-13#190]
success: tweeted on twitter confirmed by API
failure: twitter failure reported by API
Tasks:
Research how to use twitter API to implement function
implement story using rails @nohahesham 
UI
testing @karimngr 
UML @Mirna-Yacout 
Documentation @AmrARaouf

**Comment by Mirna-Yacout** [comment]
ok UML reviewed then

**Comment by ghost** [comment]
@Omar-Hossam hey omar i know this is a closed issue but i am just wondering why isn't there a cancel button next to the tweet button suppose i would like not to share half way and i just want to go back to the game??

**Comment by omar-mohyeldin** [comment]
@karimngr don't worry, there is no need for that. When the invitation link is pressed, a new tab for twitter is opened, and you are offered to either tweet or not, and still the original page there without any changes. Plus, the invitation link is not at the game, it's one of the tabs above. You could try that yourself on the master branch
