### ISSUE TITLE
C5.F2, I should be able to change the locale from english to arabic and vice versa

### ISSUE THREAD

**Issue by m0hamed** [MGhanem/smartsoft-13#193]
success: I should be able to change the locale from English to Arabic and vice versa

documentation and test: @mostafahassaan 
implementation: @NourhanMohamed 
uml: @nourhanZ 
scenario: @KareemAliRahman

**Comment by NourhanMohamed** [comment]
almost verified, check the pull request comments

**Comment by m0hamed** [comment]
please review again

**Comment by NourhanMohamed** [comment]
added a few comments, and waiting for your reply to be able to verify accordingly.. Check back the pull request

**Comment by nourhanZ** [comment]
Please indicate what does the local do after you call set_locale to make it clearer and the second one doesn't return nil so please change it

**Comment by NourhanMohamed** [comment]
check back the comments on the pull request

**Comment by m0hamed** [comment]
please review

**Comment by ghost** [comment]
@m0hamed  scenario reviewed :+1:

**Comment by NourhanMohamed** [comment]
check comments on pull request :)

**Comment by m0hamed** [comment]
please review

**Comment by NourhanMohamed** [comment]
code verified (Y)

**Comment by NourhanMohamed** [comment]
Oops, sorry I forgot a => in application controller line 37

**Comment by NourhanMohamed** [comment]
just a mild change and It'll be verified

**Comment by mostafahassaan** [comment]
doc verified

**Comment by m0hamed** [comment]
please review again

**Comment by NourhanMohamed** [comment]
code verified

**Comment by nourhanZ** [comment]
UML verified :)

**Comment by krmali** [comment]
Scenario verified

**Comment by m0hamed** [comment]
@mostafahassaan please review

**Comment by m0hamed** [comment]
@mostafahassaan please review

**Comment by mostafahassaan** [comment]
tests verified

**Comment by m0hamed** [comment]
why didnt you merge ya @mostafahassaan

**Comment by m0hamed** [comment]
@mostafahassaan can you please merge this pull request

**Comment by mostafahassaan** [comment]
sorry didn't see this. close the issue
