### ISSUE TITLE
C4.S12 - As a Developer, I can refine search results of synonyms based on demographics and other filtering criteria

### ISSUE THREAD

**Issue by NourhanMohamed** [MGhanem/smartsoft-13#195]
Success Scenarios:
Choose from available filtering criteria (Age, Education, Country, Gender) and get results tailored to your choices

Failure Scenarios:
No synonyms found based on filtering criteria. Admin may decide to limit certain subscriptions. Appropriate messages illustrating the cause of failure should be appropriately displayed to the user. 

Tasks:
C4.S12.0    Unit tests
C4.S12.1    Implementation
C4.S12.2    Documentation
C4.S12.3    Sequence Diagrams
C4.S12.4    Research Ajax

Reviewers:
Documentation: @mostafahassaan 
Scenario: @m0hamed 
Code: @adamggg 
UML Sequence Diagrams: @nourhanZ

**Comment by m0hamed** [comment]
verified

**Comment by nourhanZ** [comment]
1) Make an opt box instead of the alt box that checks [!self.approved] since you have only a return in the then part and the rest of the code is not in an else part.
2) write @synonyms, @votes instead of synonym_list and votes_count on return line between keyword model and search controller 
(The above two comments goes for C4S02 UML as well as C4S12 UML ) so please fix them in both UMLs :)

**Comment by mostafahassaan** [comment]
3 failures at search_controller_spec.rb
1) SearchController GET search should list keywords according to search
     Failure/Error: d = create_logged_in_developer()
     NoMethodError:
       undefined method `first_name=' for #Developer:0x00000005ae11b8

  2) SearchController GET search should get all keywords if no category specified
     Failure/Error: success, category = Category.add_category_to_database_if_not_exists("test")
     ActiveRecord::StatementInvalid:
       SQLite3::SQLException: no such column: categories.name: SELECT  "categories".\* FROM "categories"  WHERE "categories"."name" = 'test' LIMIT 1

  3) SearchController GET search should get only keywords in category
     Failure/Error: success, category = Category.add_category_to_database_if_not_exists("test")
     ActiveRecord::StatementInvalid:
       SQLite3::SQLException: no such column: categories.name: SELECT  "categories".\* FROM "categories"  WHERE "categories"."name" = 'test' LIMIT 1

5 failure of 28 at keyword_spec.rb
rspec ./spec/models/keyword_spec.rb:173 # Keyword should return an empty list if synonyms are unapproved
rspec ./spec/models/keyword_spec.rb:41 # Keyword should add two word keywords without spaces in between
rspec ./spec/models/keyword_spec.rb:114 # Keyword should return an empty list when searching for an unapproved keyword
rspec ./spec/models/keyword_spec.rb:181 # Keyword should return an empty list if keyword is unapproved
rspec ./spec/models/keyword_spec.rb:50 # Keyword should add keywords with categories

**Comment by adamggg** [comment]
@NourhanMohamed why can't I find the branch related to this issue? Where is it referenced?

**Comment by NourhanMohamed** [comment]
The branch was merged in sprint 1 and thus the pull request was closed. However, I'll start working on it two days from now so there is no need for you to review this now because it's gonna be modified anyways =)

**Comment by NourhanMohamed** [comment]
@m0hamed as for the error displayed to the user whenever he enters a wrong value in the number spinners, I don't see a flash as a friendly solution.. What do you think?
How can I do this better?

**Comment by m0hamed** [comment]
there are two ways of doing this. one is doing the validations yourself in javascript before sending.

the other is two generate the flash message in the js.erb file the same way you did the rendering of a partial with the entire page. if there is an error then render an additional partial that displays the flash message on top of the page

**Comment by NourhanMohamed** [comment]
I already handled this.. the thing is that I don't like it to be displayed as a flash

**Comment by mostafahassaan** [comment]
docs verified

**Comment by mostafahassaan** [comment]
tests verified

**Comment by m0hamed** [comment]
please display an error when he enters something wrong in the filters

**Comment by NourhanMohamed** [comment]
@m0hamed fixed alerts for input errors, please review =)
I tried using match but it returns something if I entered "01a" for example :/ 
for now I don't send the request, but I have no idea how to detect that for error displaying..
Tell me if your have an idea

**Comment by NourhanMohamed** [comment]
and concerning the yamli thing.. I found it down below before the body tag closes.. And I have no idea why it still delay the chart!

**Comment by NourhanMohamed** [comment]
@adamggg @nourhanZ please review, too =)

**Comment by adamggg** [comment]
@NourhanMohamed Please check pull request comments and sorry for the very late reviewing =)

**Comment by NourhanMohamed** [comment]
@adamggg please review again .. I left u a bunch of comments over the pull request please read them .. and I fixed all => to : except for a few of them that are not in my work =) also fixed all single quotes to double ones excluding those not in my work

**Comment by m0hamed** [comment]
If I search for a new keyword it should search using current filters and should not clear the filters also the filter options should be shown by default if he is searching using filters. and while you are there the button in the modal that apears in the report dilaog is too small in arabic please increase the text of the button font or better yet add a new entry in the bootstrap rtl file that increases the font size in the things of class btn. make it in its own pull request so either me or adam can review it

**Comment by m0hamed** [comment]
also add the formal slang using the tabs idea we discussed just use the normal button colours not the primary one shown in the bootstrap example

**Comment by NourhanMohamed** [comment]
@m0hamed I can't find a way to refill the filter fields with the old values passed on from the previous page.. so it looks really tedious as the user will not know that these results are filtered ones.. also if I just printed him a statement clarifying this, It'd be tedious that he's seeing empty filters while I'm printing to him that filters are applied
That's why i did remove submission of filters across keyword search

I made a pull request for increasing button text size.. and I'm working on adding formal/slang filters and I'll be updating the UML diagram accordingly when I'm done

**Comment by NourhanMohamed** [comment]
@m0hamed would you rather this or the old one?
see the attached view =)
![screenshot from 2013-04-30 11 59 42](https://f.cloud.github.com/assets/3505320/443391/e18ec008-b17c-11e2-8441-0c2b686f4089.png)

**Comment by NourhanMohamed** [comment]
The bars that are not striped are even better..

**Comment by nourhanZ** [comment]
@NourhanMohamed .. I don't have comments on the UML except one small question:
what is difference between search_keyword.blank? and search_keyword_model.blank? ?

**Comment by NourhanMohamed** [comment]
@nourhanZ search_keyword is a string, search_keyword_model is a Keyword model =)

**Comment by NourhanMohamed** [comment]
@adamggg @nourhanZ please review again .. I updated some code and updated the UML respectively

**Comment by NourhanMohamed** [comment]
@mostafahassaan please re-review I updated docs and tests

**Comment by mostafahassaan** [comment]
docs verified

**Comment by mostafahassaan** [comment]
sorry pressed the button by mistake..

**Comment by NourhanMohamed** [comment]
@m0hamed @nourhanZ @adamggg @mostafahassaan please review =)

**Comment by mostafahassaan** [comment]
@NourhanMohamed please fix conflics and tag again for tests :)

**Comment by mostafahassaan** [comment]
docs verified again

**Comment by m0hamed** [comment]
when I search for a keyword then change the filters and then click the search button the page refreshes and the results are not filtered according to the criteria entered even though they are visible

**Comment by NourhanMohamed** [comment]
@m0hamed it works here.. but I guess there is a problem with popovers.. they don't show what they are supposed to show -.-'
I'm trying to fix them now, though =)

**Comment by NourhanMohamed** [comment]
@m0hamed fixed the tooltips.. please re-review =)

**Comment by NourhanMohamed** [comment]
@m0hamed @nourhanZ @mostafahassaan @adamggg PLEASE review

**Comment by adamggg** [comment]
@NourhanMohamed Code reopened =)

**Comment by NourhanMohamed** [comment]
@adamggg check back .. and I left you some replies on your comments please check them out, too =)

**Comment by mostafahassaan** [comment]
Nourhan I have NEVER had to scroll down this much to comments! :D

**Comment by mostafahassaan** [comment]
tests and docs verified :)

**Comment by NourhanMohamed** [comment]
lol yeah I know it's a long journey to down here :D

**Comment by m0hamed** [comment]
verified. please add formality to synonyms in the populate file because when I click formal or slang I get no synonyms at all so please add that to the populate task

**Comment by adamggg** [comment]
@NourhanMohamed did you fix what I told you since the label is still untouched? =D

**Comment by NourhanMohamed** [comment]
@adamggg the label is pending :D

**Comment by NourhanMohamed** [comment]
@nourhanZ review UML pleaaaaaaaaaaaaaaaaaaaaaaaaase =D

**Comment by nourhanZ** [comment]
UML reopen, I think yoou removed search method from search_controller so please change it in UML C4S02 and in any other UML that you're using it in

**Comment by NourhanMohamed** [comment]
@nourhanZ fixed comment.. please review again =)

**Comment by nourhanZ** [comment]
UML verified =)

**Comment by nourhanZ** [comment]
I reopened it just to place the filters in the story without reference and then tag me to review it :)

**Comment by NourhanMohamed** [comment]
@nourhanZ please review

**Comment by adamggg** [comment]
Code verified =)

**Comment by nourhanZ** [comment]
UML verified

**Comment by nourhanZ** [comment]
Merged close the pull request

**Comment by NourhanMohamed** [comment]
@nourhanZ please review uml for search quota
@mostafahassaan please review docs
@adamggg please review code

**Comment by mostafahassaan** [comment]
verified

**Comment by nourhanZ** [comment]
UML verified =)

**Comment by NourhanMohamed** [comment]
@mostafahassaan please review tests
@m0hamed please review scenario

**Comment by mostafahassaan** [comment]
tests verified

**Comment by NourhanMohamed** [comment]
@adamggg please review again =)

**Comment by m0hamed** [comment]
could you please increase the size of the formal/slang buttons in arabic only

**Comment by adamggg** [comment]
Verified =)

**Comment by NourhanMohamed** [comment]
@m0hamed check back
btw the filter script is not working because of someone else's work.. and the part of the word add doesn't look good in english and the button is split across another line in arabic!

**Comment by m0hamed** [comment]
cannot be automatically merged

**Comment by m0hamed** [comment]
verified

**Comment by NourhanMohamed** [comment]
closing issue upon merge ...
