### ISSUE TITLE
C4.S06 - As a Developer, I can view the visuals/stats about the age distribution of people voted for this synonym

### ISSUE THREAD

**Issue by nourhanZ** [MGhanem/smartsoft-13#201]
Success: 
Get statistics displayed visually about those gamers who added or voted for the different synonyms

Failure:
No failures unless Admin decides to limit to certain subscriptions

Reviewers:
Documentation Reviewer @mostafahassaan 
UML/Design Reviewer @Khloud-Khalid 
Implementation Reviewer @NourhanMohamed 
Scenario Reviewer @m0hamed

Tasks:
C4.S06.1 - Sequence Diagram 
C4.S06.2 - Unit Tests
C4.S06.3 - Implementation 
C4.S06.4 - Documentation 
C4.S06.5 - User Interface

**Comment by NourhanMohamed** [comment]
since u merged ur 4 visual stats branches together, I'm reviewing them here (#202) and verifying all whenever you're done with them all
see pull request comments
https://github.com/MGhanem/smartsoft-13/pull/312/files
