### ISSUE TITLE
C4.S07 - As a Developer, I can view the visuals/stats about the educational level of people voted for this synonym

### ISSUE THREAD

**Issue by nourhanZ** [MGhanem/smartsoft-13#202]
Success: 
Get statistics displayed visually about those gamers who added or voted for the different synonyms

Failure:
No failures unless Admin decides to limit to certain subscriptions

Reviewers:
Documentation Reviewer @mostafahassaan 
UML/Design Reviewer @Khloud-Khalid 
Implementation Reviewer @NourhanMohamed 
Scenario Reviewer @m0hamed

Tasks:
C4.S07.1 - Sequence Diagram 
C4.S07.2 - Unit Tests
C4.S07.3 - Implementation 
C4.S07.4 - Documentation 
C4.S07.5 - User Interface

**Comment by nourhanZ** [comment]
@NourhanMohamed @m0hamed @mostafahassaan @Khloud-Khalid please review :)

**Comment by NourhanMohamed** [comment]
since u merged ur 4 visual stats branches together, I'm reviewing them here and verifying all whenever you're done with them all
see pull request comments
https://github.com/MGhanem/smartsoft-13/pull/312/files

**Comment by m0hamed** [comment]
verified

**Comment by mostafahassaan** [comment]
please stick to the documentation convention :)
 # author:
  #   Mostafa Hassaan
  # description:
  #   function returns a hash with all keywords followed by a developer
  # params:
  #   gamer_id: id used to get the developer
  # success:
  #   returns a hash containing all keywords followed by the given developer
  # failure:
  #   returns empty hash if the developer doesn't follow any keywords

**Comment by mostafahassaan** [comment]
please stick to the documentation convention :)
 # author:
  #   Mostafa Hassaan
  # description:
  #   function returns a hash with all keywords followed by a developer
  # params:
  #   gamer_id: id used to get the developer
  # success:
  #   returns a hash containing all keywords followed by the given developer
  # failure:
  #   returns empty hash if the developer doesn't follow any keywords

**Comment by nourhanZ** [comment]
@NourhanMohamed  @m0hamed @mostafahassaan please review :)

**Comment by mostafahassaan** [comment]
You haven't fixed the documentations yet nourhan, I've had to reopen. please fix quickly and tag again  :)

**Comment by mostafahassaan** [comment]
test verified

**Comment by m0hamed** [comment]
please fix that percentage sign that appears before the text

**Comment by NourhanMohamed** [comment]
check pull request comments

**Comment by nourhanZ** [comment]
@m0hamed please review :)
@NourhanMohamed I didn't see your comments before pushing again I will fix them an then tag you again :)
@mostafahassaan I changed and added some test so please check them again :)
@Khloud-Khalid please review UMLS :)

**Comment by m0hamed** [comment]
also stop the cursor from becoming a hand on the entire row. like when you put your mouse on any part of the row that shows the charts it should not appear asif its clickable

**Comment by nourhanZ** [comment]
@m0hamed I fixed your comments please review again :)
@NourhanMohamed fixed your comments and a little more :D please review :)
@mostafahassaan fixed your comments on docs please review them and tests as well :)
@Khloud-Khalid please review :)

**Comment by Khloud-Khalid** [comment]
UML verified :)

**Comment by m0hamed** [comment]
education stats is not appearing correctly in english

**Comment by nourhanZ** [comment]
@m0hamed It's appearing correctly and I used inspect element and its container is wider than the text so I don't really see any problem :)

**Comment by NourhanMohamed** [comment]
@nourhanZ check pull request comments 
@m0hamed can we merge her before I'm done? since she has my branch in her work?

**Comment by nourhanZ** [comment]
@NourhanMohamed fixed the code conventions again please review :)

**Comment by nourhanZ** [comment]
@mostafahassaan please review the tests and documentation

**Comment by nourhanZ** [comment]
@m0hamed can you inspect the svg element and tell me its width

**Comment by mostafahassaan** [comment]
docs verified

**Comment by mostafahassaan** [comment]
I just want to make sure that you know that some of salma's work is being pushed with this branch @m0hamed @NourhanMohamed

**Comment by nourhanZ** [comment]
Which part of salma's work is being pushed with this branch?!!! @mostafahassaan

**Comment by nourhanZ** [comment]
@m0hamed please review :)

**Comment by nourhanZ** [comment]
@mostafahassaan please review the tests

**Comment by m0hamed** [comment]
verified

**Comment by NourhanMohamed** [comment]
see pull request comments , and pull my branch for the latest changes..

**Comment by mostafahassaan** [comment]
verified tests

**Comment by nourhanZ** [comment]
@NourhanMohamed please review :)

**Comment by NourhanMohamed** [comment]
code verified

**Comment by m0hamed** [comment]
verified
