### ISSUE TITLE
C3.S05-Should be able to manage subscription model

### ISSUE THREAD

**Issue by nohahesham** [MGhanem/smartsoft-13#203]
success:Through account settings, the developer can change his subscription model.
failure:Payment issues.
Tasks:
1-Research
2-UML @Fattouh92 
3-Implement @NourhanMohamed 
4-Test @m0hamed 
5-Documentation @SalmaFG

**Comment by NourhanMohamed** [comment]
@nohahesham I'm your code reviewer not Omar, tag me instead

**Comment by nohahesham** [comment]
This issue was repeated
