### ISSUE TITLE
C3.S18-As a Developer, I Should be able to share my projects with other users

### ISSUE THREAD

**Issue by nohahesham** [MGhanem/smartsoft-13#204]
Success:by adding an existing user email, I can share my project with him and he can view and modify the project.

Failure:The email entered is not valid. Should send an email to the developer inviting him to join arability to be able to view the project shared with him.

Tasks:
1-Research
2-UML @Fattouh92 
3-Implement @Omar-Hossam 
4-Test @m0hamed 
5-Documentation @SalmaFG

**Comment by NourhanMohamed** [comment]
@nohahesham I'm your code reviewer not Omar, tag me instead

**Comment by nohahesham** [comment]
no omar is my new code reviewer ,tamer just told me that c3 is now with c2
