### ISSUE TITLE
C3.S12 - As a Developer, I should be able to edit my project.

### ISSUE THREAD

**Issue by salmafg** [MGhanem/smartsoft-13#205]
Success:
He will be able to edit the project details and save it.

Failure:
None.

Tasks:
1. UML @Fattouh92 
2. Functionality @nohahesham 
3. Documentation @AmrARaouf 
4. Scenario @m0hamed 
5. Tests @AmrARaouf

**Comment by salmafg** [comment]
@m0hamed @Fattouh92 @nohahesham @AmrARaouf

**Comment by m0hamed** [comment]
this issue doesnt have a pull request why is it pending

**Comment by salmafg** [comment]
It uses the same pull request as #77 but I forgot to tag it then.
Check now.

**Comment by m0hamed** [comment]
اللغة is not correct either but nothing comes to mind. Also it should not be الفئات or categories since it is a single category.

**Comment by m0hamed** [comment]
The maximum age is not included in the list is not a descriptive error message for the range issues

**Comment by m0hamed** [comment]
also categories disappear when the an error occurs

**Comment by salmafg** [comment]
@m0hamed I fixed most stuff you mentioned but concerning the اللغة I think it's perfect. Check now.

**Comment by m0hamed** [comment]
الحد الادنى للسن ليس خيارا مقبولا should say that the minimum age is 10 and same for the max age. also why is the age required but not the category or "language". what is so special about the age.

**Comment by m0hamed** [comment]
also if I get an error on the add project page there is no way not to choose a category because one is already chosen for me

**Comment by m0hamed** [comment]
the title new project should not change color if it is not a link

**Comment by m0hamed** [comment]
in the edit page I have no way to edit the project without choosing a category

**Comment by m0hamed** [comment]
on the edit project page at the bottom it says "show" even when arabic

**Comment by salmafg** [comment]
I don't get your first comment but regarding the 2nd, should I require the
category and language or unrequire the age??

**Comment by salmafg** [comment]
@m0hamed Check now

**Comment by m0hamed** [comment]
that is what we are discussing with adam. I also think that the project should get a country and an educatational level

**Comment by m0hamed** [comment]
I think they should all be optional I think

**Comment by salmafg** [comment]
I think you have a point here. I think we should vote on it then.

**Comment by m0hamed** [comment]
which comment did you not understand

**Comment by m0hamed** [comment]
should I review or not since you havent answered my question. did you fix all my comments or did you miss something

**Comment by salmafg** [comment]
Yes I did. Please review.

**Comment by salmafg** [comment]
Please keep in mind that the part regarding Noha's subscription is still
commented because otherwise it would not work.

**Comment by m0hamed** [comment]
really because my coments have not been fixed yet I still get "الحد الادنى للسن ليس خيارا مقبولا" and I still cant remove the category from a project. also if I have an error I must choose a category to continue. Also you should pull noha'sbranch if you want to integrate her code if it is not working then make her fix it. I can only review finished code.

**Comment by m0hamed** [comment]
I am reopening this. please donot change to pending again untill you have fixed all the comments

**Comment by salmafg** [comment]
What's wrong with the ÇáÍÏ ÇáÇÏäì ááÓä áíÓ ÎíÇÑÇ ãÞÈæáÇ ?

**Comment by m0hamed** [comment]
it is not very informative. how can the user know that the minimum age is 10 and he entered an age less than that. please have your errors be more descriptive

**Comment by salmafg** [comment]
Wouldn't it be optional? That means I should remove the validations I guess

**Comment by salmafg** [comment]
Ashraf

**Comment by salmafg** [comment]
@m0hamed Please review

**Comment by m0hamed** [comment]
didnt we find that having two active record entries messes things up. why did you create an new entry? its like you enjoy ruining other people's work

**Comment by m0hamed** [comment]
also why is no one else reviewing this code. where are the other reviewers

**Comment by salmafg** [comment]
@m0hamed What part are you talking about?

**Comment by salmafg** [comment]
They're reviewing over the pull request.

**Comment by salmafg** [comment]
@m0hamed If you're started reviewing please refresh the page or repull the
branch or whatever because there was a problem and I just fixed it. Sorry
about that.

**Comment by salmafg** [comment]
@m0hamed Check now please.

**Comment by m0hamed** [comment]
it should be called taget country and al balad al mostahdafa in arabic so that it is easier to understand what is country

**Comment by m0hamed** [comment]
same for educational level

**Comment by m0hamed** [comment]
reduce the font size of the english buttons and increase the font size for the arabic ones. also in the english form the buttons should on the opposite side of the text not under it like in the arabic form

**Comment by salmafg** [comment]
@m0hamed Concerning the font size, I thought someone was gonna fix it for
the whole website?

**Comment by m0hamed** [comment]
it is fixed already but some places still have the same font size such as
stuff in buttons and so on. so fix it like I said

On Sun, Apr 28, 2013 at 1:16 PM, Salma Farag Galal <notifications@github.com

> wrote:
> 
> @m0hamed Concerning the font size, I thought someone was gonna fix it for
> the whole website?
> 
> On Sun, Apr 28, 2013 at 10:55 AM, Mohamed Ashraf

**Comment by salmafg** [comment]
@m0hamed I have fixed the target thing but for the font, the form doesn't look good with the smaller English text because it's too small relevant to the textfields and other components.
Please review.

**Comment by m0hamed** [comment]
I didnt say the entire form I just said the buttons. also did you fix the placement of the buttons

**Comment by salmafg** [comment]
Ook got ya.
I will finish that and tag you again.

**Comment by salmafg** [comment]
@m0hamed Done.

**Comment by m0hamed** [comment]
please add gender to project

**Comment by m0hamed** [comment]
I merged the pull request for the gender migration so you can add gender now. also you are storing the country and the educational level in lowercase while kareem ali stores it using the first letter upper case of each word please do the exact same thing for consistency. it is nice the way you divided the form so as to make it more understandable and it looks good. however please increase the size of the text in the buttons in the arabic form but not in the english form

**Comment by salmafg** [comment]
@m0hamed Thanks. Should I add "both" to the gender? Because websites usually target
both genders.

**Comment by salmafg** [comment]
@m0hamed But for that to work we will have to change the column type because it's
boolean right now.

**Comment by salmafg** [comment]
@m0hamed

**Comment by salmafg** [comment]
@m0hamed

**Comment by m0hamed** [comment]
if you have any issues you may use the mailing list so that your question is not lost to github spam

**Comment by m0hamed** [comment]
the values for male and female should be lowercase since this is how it is stored in the database. I told you to see how kareem does it

**Comment by m0hamed** [comment]
this is almost scenario verified

**Comment by m0hamed** [comment]
also please pull tato's branch so that I can see if the data is actually stored or not. and how is it stored

**Comment by m0hamed** [comment]
also I think category is not being stored correctly. If I edit a project and set the category to please choose the category is not removed

**Comment by salmafg** [comment]
@m0hamed Check now

**Comment by m0hamed** [comment]
verified

**Comment by m0hamed** [comment]
this cannot be merged because all the issues are in one pull request. when the last issue in the pull request is done then merge the pull request
