### ISSUE TITLE
C3.S05 - As a Developer, I should be able to manage my subscription model

### ISSUE THREAD

**Issue by nohahesham** [MGhanem/smartsoft-13#206]
Success:
Through account settings, the developer can change his subscription model.

Failure:
Payment issues.

Tasks:
1- Research
2- UML @Fattouh92 
3- Implement @Omar-Hossam 
4- Test @m0hamed 
5- Documentation @SalmaFG

**Comment by salmafg** [comment]
@nohahesham Documentation verified.

**Comment by m0hamed** [comment]
Please make it more descriptive in the subscription model choice. Make sure that the user understands what these limits mean. dont say limit for word search but say the maximum number of serches you can make is and make sure the number is "x/ per month" same for all the other limits. also the arabic  text is even less descriptive

**Comment by m0hamed** [comment]
please always change the labels

**Comment by m0hamed** [comment]
Make the descriptions clearer for the developer. the word follow limit has no relation to projects so it shouldnt say so in the description. The success message should be shown in green. You should update the populate task to add the word search limit to the subscription

**Comment by m0hamed** [comment]
The maximum number for adding words to your project is: should be The maximum number of words per project
in arabic the tab should be called 25tar nezam al daf3 not e5tar nezamak.
الحد الأقصى لانشاء المشاريع هي should be 3adad al masharee3. Also لقد تم إختيار نظامك بنجاح should be lakad 3'ayart nezamak ela <name of subscription model>.

The subscription model name should be translated in arabic

**Comment by nohahesham** [comment]
the model name changes according to the database how will i translate it?

**Comment by nohahesham** [comment]
@m0hamed

**Comment by m0hamed** [comment]
please change the labels if you want me to review.

**Comment by m0hamed** [comment]
you may add a migration to add an english name and arabic name to the model and update the populate task. so that is sets the english and arabic name

**Comment by m0hamed** [comment]
please donot write the limit as the maximum number of word follow or word search, since this is not easy to understand. make it you can search for x words per month, or you can follow x words per month. do the same for the remaining limits

**Comment by nohahesham** [comment]
i dnt get the last comment? u want me to change it again @m0hamed ?

**Comment by m0hamed** [comment]
how is this story going ya @nohahesham

**Comment by nohahesham** [comment]
plz review it @m0hamed :)

**Comment by m0hamed** [comment]
please change the populate task to add the english name and arabic name and it will probably throw an exception unless you add them to the attr_accessible

**Comment by m0hamed** [comment]
"The number of words you can add to you project is:"
you misspelled your.
also you should change the arabic text the same way you changed the english text. for example instead of "الحد الأقصى للبحث عن الكلمات في مشروعك هي:" you can say 3adad al kalemat alaty yomkenoka al ba7th 3anha howa. and so on in the other limits. also the tab should not say choose subscription model but should just say subscribtion model. same for arabic

**Comment by nohahesham** [comment]
@m0hamed 
@Fattouh92 
plz revieww

**Comment by m0hamed** [comment]
verified
