### ISSUE TITLE
C3.S27 - As a Developer, I should be able to view my project.

### ISSUE THREAD

**Issue by salmafg** [MGhanem/smartsoft-13#209]
Pull request #385 

Success:
Opens the project page that holds all functionalities that can be applied on a project.

Failure:
None.

Tasks:
1. UML @Fattouh92 
2. Documentation @AmrARaouf 
3. Scenario @m0hamed
4. Implementation@nohahesham 
5. Tests @AmrARaouf

**Comment by salmafg** [comment]
@Fattouh92  @AmrARaouf @m0hamed @nohahesham 
Please review

**Comment by m0hamed** [comment]
why was this reopened in the first place. what did you change

**Comment by salmafg** [comment]
@m0hamed The tests and UML, but I guess I should pend the other stuff too?

**Comment by m0hamed** [comment]
either way please pull master. and since there is no scenario to review this is verified

**Comment by abulazm22** [comment]
Update UML with from the cahnges in code
