### ISSUE TITLE
C3.S16 - As a developer, I should be able to view projects others shared with me.

### ISSUE THREAD

**Issue by abulazm22** [MGhanem/smartsoft-13#210]
Success: A page listing all the projects others have shared with me ordered descendingly by the creation date.
Failure: I can't see a project shared with me
1)UML @Mirna-Yacout 
2)Implement @nohahesham 
3)Test @m0hamed 
4)Documentation @SalmaFG

**Comment by m0hamed** [comment]
This cannot be merged into master untill the create project is updated from @SalmaFG

**Comment by m0hamed** [comment]
verified

**Comment by m0hamed** [comment]
this throws an exception if the project has no educational level which is optional.

**Comment by abulazm22** [comment]
Ashraf I just tried it out didn't throw any error. What is the error?

**Comment by abulazm22** [comment]
And Please don't tell me it is an error in create. I am going pending again :)

**Comment by m0hamed** [comment]
undefined method `size' for nil:NilClass
264                 <% if project1.education_level.size == 0 %>

here is the exception. as I said it only hapens if a project doesnt have an educational level. you are trying to see if a project has an educational level and you can use the methods present? and blank? that can be called on nil without raising an exception for example

```
if project.education_level.blank?
  do what you would do if it is nil or empty string
else
  do what you would do if not nil or empty string
end
```

**Comment by m0hamed** [comment]
things go really bad in the index view if I have two projects. some things are duplicated and there is an unshare button in the index page. also the text is too big in the english language. please make sure the text is only big in the arabic side

**Comment by m0hamed** [comment]
verified
