### ISSUE TITLE
C1S28 - karimngr - As an admin i should be able to sign in

### ISSUE THREAD

**Issue by ghost** [MGhanem/smartsoft-13#348]
Success: Enter a valid admin username and password, get access to all admin privileges.

Failure: Invalid username or password, admin is notified where the error occurred.

Tasks:
1- integrate admin users with gamers
2- document the integration between admin users and gamers
3- test the integration between admin users and gamers

Reviewers:
@AmrARaouf 
@Omar-Hossam 
@Mirna-Yacout 
@m0hamed

**Comment by AmrARaouf** [comment]
where are your tests?

**Comment by m0hamed** [comment]
please make sure that you have an entry in the populate task to create an admin so I can test it and for the demo

**Comment by m0hamed** [comment]
for some reason I am not able to login.

**Comment by m0hamed** [comment]
ok I logged in I am not sure why it was not working but anyway where is the admin panel. You said there would be a tab at the top. where is it

**Comment by m0hamed** [comment]
The admin panel is not visible in english

**Comment by ghost** [comment]
@m0hamed it is now fixed

**Comment by ghost** [comment]
and the entry is karim@gmail.com

**Comment by m0hamed** [comment]
@karimngr did you fix the admin panel not being visible in english

**Comment by ghost** [comment]
yes @m0hamed

**Comment by m0hamed** [comment]
verified

**Comment by ghost** [comment]
@AmrARaouf  this story doesnt have tests as it is using devise and it is already tested
