### ISSUE TITLE
C5S08 , C5S09 - karimngr - As an admin, I should be able to view the gamer profiles and their achievments & As an admin, I should be able to view the developer usage

### ISSUE THREAD

**Issue by ghost** [MGhanem/smartsoft-13#349]
Story C5S08:
Success: Admin will be able to view the gamers' username, email, trophies count, prizes count and votes.

Failure: No gamers are still available on the system.

Tasks:
1- implement view gamer profiles procedure
2- document view gamer profiles procedure
3- test view gamer profiles procedure
4- design uml for view gamer profiles procedure

Story C5S09:
Success: Admin will be able to view the developers' username, email, project count and words count per project.

Failure: No developers are still available on the system.

Tasks:
1- implement view developer usage procedure
2- document view developer usage procedure
3- test view developer usage procedure
4- design uml for view developer usage procedure

Reviewers:
@AmrARaouf 
@Omar-Hossam 
@Mirna-Yacout 
@m0hamed

**Comment by m0hamed** [comment]
titles should not change colour when hovered over if it is not clickable. the pagination should not say older/ newer but should show the page numbers that should be clickable to go to a page in the middle

**Comment by m0hamed** [comment]
also why does one pull request have all the stories.

**Comment by m0hamed** [comment]
there is something called عرض المشارييع that has a list of projects shouldnt that be paginated since we would have a huge number of projects

**Comment by m0hamed** [comment]
there are duplicate projects in the project listing

**Comment by m0hamed** [comment]
verified

**Comment by m0hamed** [comment]
verified
