### ISSUE TITLE
C5.S03 - As a Developer / Gamer / Guest I should be able to view the homepage. 

### ISSUE THREAD

**Issue by mostafahassaan** [MGhanem/smartsoft-13#350]
_Success:_ After entering the website url and pressing enter, users should view information about the game side and the developer side with a carousel at the top of the page containing info about various sections of the website

_Failure:_ None.

Tasks:
1. Scenario: @m0hamed 
2. Implementation: @NourhanMohamed

**Comment by mostafahassaan** [comment]
If both reviewers verify this issue, do not close it. There will be changes to the homepage according to what the rest of the company want.
Also, the carousel only has one slide, I'll update it according when people start sending me images of what they want. 
The logo is missing, I'm waiting on adam.

**Comment by mostafahassaan** [comment]
@m0hamed @NourhanMohamed please review :)

**Comment by NourhanMohamed** [comment]
@mostafahassaan please reference this issue from the pull request for us to begin reviewing =)

**Comment by m0hamed** [comment]
did you fix the navbar, made the icons spaced out and made the word english smaller and the word 3arabi bigger

**Comment by abulazm22** [comment]
Hassaan says no.

**Comment by m0hamed** [comment]
also you should tag your test and uml and doc reviewers and they should verify that it doesnt require those things

**Comment by NourhanMohamed** [comment]
check pull request comments

**Comment by mostafahassaan** [comment]
last commit fixed convention*

**Comment by mostafahassaan** [comment]
@NourhanMohamed please review

**Comment by NourhanMohamed** [comment]
check pull request comments

**Comment by m0hamed** [comment]
we said developers should see the game tab in their navbar and gamers should see developers in the nav bar. also the arabic text is too small in the navbar. make it bigger

**Comment by mostafahassaan** [comment]
@m0hamed review please

**Comment by mostafahassaan** [comment]
@NourhanMohamed

**Comment by NourhanMohamed** [comment]
Use ruby path helpers

**Comment by nourhanZ** [comment]
UML is not required for this story

**Comment by m0hamed** [comment]
please increase the size of the word 3arabi and decrease the size of the word english in the task bar

**Comment by mostafahassaan** [comment]
@m0hamed review again please

**Comment by mostafahassaan** [comment]
@nourhanZ @NourhanMohamed !!

**Comment by NourhanMohamed** [comment]
check pull request comments!

**Comment by m0hamed** [comment]
please increase the size of the arabic font in the buttons in the carousel, the homepage and in the sign in dropdown from the navbar

**Comment by mostafahassaan** [comment]
review please

**Comment by mostafahassaan** [comment]
no, wait. don't yet.

**Comment by mostafahassaan** [comment]
There is a small issue with the scenario @m0hamed. I know what the problem is, I'm too tired to fix it right now. I'll show it to you tomorrow because I need help with it. @NourhanMohamed You can review code, I don't know how the paths weren't made correctly walahy, I corrected them beside you today!

**Comment by mostafahassaan** [comment]
@NourhanMohamed @m0hamed @zoheiry review please

**Comment by zoheiry** [comment]
What am i supposed to review, there are neither tests nor documentation ?

**Comment by mostafahassaan** [comment]
It's a view. I just need you to verify that it doesn't need docs or tests.

**Comment by m0hamed** [comment]
verified

**Comment by zoheiry** [comment]
okay, it seems that you dont need documentation or testing, your all set to go

**Comment by NourhanMohamed** [comment]
code verified

**Comment by NourhanMohamed** [comment]
@mostafahassaan pull master and resolve conflicts for me to merge =)

**Comment by mostafahassaan** [comment]
thanks nourhan :D 
@NourhanMohamed @m0hamed @nourhanZ review please :)

**Comment by NourhanMohamed** [comment]
@mostafahassaan fix the drop downs of the autocomplete to be non-inverse and fix developer link

**Comment by mostafahassaan** [comment]
@m0hamed review please

**Comment by m0hamed** [comment]
verified

**Comment by m0hamed** [comment]
verified
