### ISSUE TITLE
C5S10 , C5S11 - karimngr - As an admin, I should be able to add another admins & As an admin, I should be able to remove another admins

### ISSUE THREAD

**Issue by ghost** [MGhanem/smartsoft-13#351]
Story C5S10:
Success: after signing in with the admin username and password, the admin will have a link that can be clicked to access the admin panel. Now he will have the option to upgrade other system users via entering the email of the user in an auto-complete box. An email should be sent to the admin that was invited to inform him that he's currently an admin.

Failure: If user doesn't exist on the system, a message will be displayed to the inviting admin.

Tasks:
1- implement add another admins
2- document add another admins
3- test add another admins
4- design uml for add another admins

Story C2S11:
Success: after signing in with the admin username and password, the admin will have a link that can be clicked to access the admin panel. Now he will have the option to view current admins and remove any of them using a button beside each existing admin. If no admins are there display an appropriate message.

Failure: none.

Tasks:
1- implement remove another admin
2- document remove another admin
3- test remove another admin
4- design uml for remove another admin

Reviewers:
@AmrARaouf 
@Omar-Hossam 
@Mirna-Yacout 
@m0hamed

**Comment by m0hamed** [comment]
please dont show me myself in the list of admins

**Comment by ghost** [comment]
@m0hamed  please review #349  is also included in the commits

**Comment by m0hamed** [comment]
verified
