### ISSUE TITLE
C5.S23 - As a Developer / Gamer / Guest I should see correct Exception Handling and Catching Errors.

### ISSUE THREAD

**Issue by mostafahassaan** [MGhanem/smartsoft-13#352]
_Success:_ when an exception is caught, the page redirects to the page where the exception was thrown.

_Failure:_ None.

Tasks:
1. Documentation: @zoheiry 
2. Tests: @zoheiry 
3. Scenario: @m0hamed 
4. Implementation: @NourhanMohamed

**Comment by mostafahassaan** [comment]
@zoheiry @m0hamed @nourhanZ @NourhanMohamed please review :)

**Comment by zoheiry** [comment]
Docs verified for now

**Comment by zoheiry** [comment]
Test Reopened...
1 Failure:
 ApplicationController should redirect to home page when an invalid url is thrown
 Failure/Error: login_gamer(d.gamer)
 NoMethodError:
   undefined method `env' for nil:NilClass

**Comment by mostafahassaan** [comment]
it's working, just make sure you rake db:migrate and rake db:test:prepare

**Comment by mostafahassaan** [comment]
when running the test, rspec to that file only

**Comment by mostafahassaan** [comment]
ma3rafsh i don't know why it wouldn't work 3andak

**Comment by mostafahassaan** [comment]
@m0hamed @nourhanZ @NourhanMohamed please review

**Comment by NourhanMohamed** [comment]
check pull request comment

**Comment by nourhanZ** [comment]
UML verified :)

**Comment by NourhanMohamed** [comment]
check pull request comment

**Comment by NourhanMohamed** [comment]
code verified

**Comment by m0hamed** [comment]
exceptions are not caught

**Comment by mostafahassaan** [comment]
@m0hamed @nourhanZ @NourhanMohamed @zoheiry review please

**Comment by NourhanMohamed** [comment]
code verified

**Comment by m0hamed** [comment]
make the email that is sent at the time of the exception contain the name of the exception. the alerts donot disapear after 5 secs. also the alerts when closed currently bump the entire page up which looks bad. it is best if  you do it the same like nourhan M in the report story. the alert appears above the page and when closed it doesnt affect the page. her story should be in master by now so you can see it in the keyword profile or just checkout her branch

**Comment by nourhanZ** [comment]
UML verified :)

**Comment by zoheiry** [comment]
tests verified

**Comment by m0hamed** [comment]
verified
