### ISSUE TITLE
[C5S4] As a gamer I should be able to reset my password

### ISSUE THREAD

**Issue by adamggg** [MGhanem/smartsoft-13#354]
Success:
I should have a forget password link in the sign in page. Upon clicking I should be redirected to a page where I can enter my email. Upon clicking verify an auto generated password reset token should be sent to the user and the users should be able to click a link to visit the view to set the new password. The user can then change his password through the view in the link in the email.

Failure:
User entered a non-existing email in our database. If the user didn't recieve an email he should be able to reset it again.

Scenario Reviewer: @KareemAliRahman
Implementation Reviewer: @NourhanMohamed 
UML Reviewer: @Khloud-Khalid
Documentation Reviewer: @zoheiry

**Comment by NourhanMohamed** [comment]
see pull request comment.. almost verified

**Comment by NourhanMohamed** [comment]
code verified

**Comment by zoheiry** [comment]
Look like everything is in the views, no tests or docs needed, Verified

**Comment by Khloud-Khalid** [comment]
UML verified.

**Comment by krmali** [comment]
@adamggg , the error that appears when trying to reset and the email is already found looks bad , it's font is very big

**Comment by adamggg** [comment]
@KareemAliRahman This is the same errors that are displayed across the site in any view that uses devise messages, its in the sign up, sign in, edit, guest signup. Changing it will be inconsistent, wouldn't it?

**Comment by krmali** [comment]
@adamggg , I guess you can change the css text-size of that specific view by jquery, can you ?
try to do this: $('.alert').css('text-size','25px').

**Comment by adamggg** [comment]
@KareemAliRahman what do you mean by already found?

**Comment by krmali** [comment]
@adamggg, change the button and make it smaller, "Send me reset password instructions" to only "rest password" and in the arabic page chage it to "إعادة تعيين كلمة السر".

**Comment by krmali** [comment]
@adamggg, scenario verified
