### ISSUE TITLE
C2S05 As a guest I could send invitations to play the game to my friends through my facebook timeline (RO)

### ISSUE THREAD

**Issue by AmrARaouf** [MGhanem/smartsoft-13#356]
Success:

Failure:

Tasks:

1- Refining implementation @Omar-Hossam @SalmaFG @karimngr @Mirna-Yacout

**Comment by ghost** [comment]
@AmrARaouf  edit the issue and add the success and failure scenarios to be able to verify

**Comment by ghost** [comment]
@verified
