### ISSUE TITLE
[C5S5] As a gamer I should be able to recieve a verification email upon signup

### ISSUE THREAD

**Issue by adamggg** [MGhanem/smartsoft-13#357]
Success:
an email should be sent as a sign up second change that is sent to the user email with a verification token. Upon clicking the verification mail, the user should click the link provided in the email and should be redirected to the signed in version of the website. The text should be displayed in the appropriate language according to the current locale

Failure:
If the user didn't recieve an email he should have a button that allows resending the confirmation email

Scenario Reviewer: @KareemAliRahman
Implementation Reviewer: @NourhanMohamed 
UML Reviewer: @Khloud-Khalid
Documentation Reviewer: @zoheiry

**Comment by zoheiry** [comment]
No tests or documentation needed, Verified

**Comment by NourhanMohamed** [comment]
one comment pending for verify :D

**Comment by adamggg** [comment]
@NourhanMohamed check again please =)

**Comment by NourhanMohamed** [comment]
code verified =)

**Comment by Khloud-Khalid** [comment]
@adamggg there should be a dotted line between the if and else part in the condition box. also, what is that :draw thing at the bottom? :D

**Comment by adamggg** [comment]
@Khloud-Khalid Please check now =)

**Comment by krmali** [comment]
@adamggg, Adam I tried to sign up and then the mail sent successfully and everything look fine, I have a question I see the sign_up_status is nil either before or after the sign up confirmation mail, why does not this column change ?

**Comment by krmali** [comment]
and Can you tell the user that he will receive a verification email

**Comment by adamggg** [comment]
The user is notified in the alert that he gets sent an email and that
column has something to do with devise methods and configuration =)

**Comment by adamggg** [comment]
@Khloud-Khalid Please review!

**Comment by krmali** [comment]
@adamggg , the user is not notified, when he sign up he is redirected to the home page without any notifictation except when trying to login without confirming.

**Comment by adamggg** [comment]
@KareemAliRahman check the bottom of the page, Hassan broke something when he was doing the home page and now alerts don't appear on the home page. Check again =)

**Comment by krmali** [comment]
@adamggg, the alert appears at the buttom of the page.

**Comment by Khloud-Khalid** [comment]
UML verified.

**Comment by adamggg** [comment]
@KareemAliRahman please review scenario! =D

**Comment by krmali** [comment]
@adamggg, scenario verified
