### ISSUE TITLE
C5S24 As a guest I can sign up with facebook

### ISSUE THREAD

**Issue by AmrARaouf** [MGhanem/smartsoft-13#358]
Success:
connects account through api, redirected to the sign up page with all his information readily filled in

Failure:
error reported by the api

Tasks:

1- Research
2- Implementation @Omar-Hossam @karimngr 
3- Documentation @SalmaFG 
4- Testing @SalmaFG 
5- UML @Mirna-Yacout

**Comment by ghost** [comment]
@AmrARaouf  please fix the labels for the issue

**Comment by salmafg** [comment]
Documentation verified.

**Comment by salmafg** [comment]
2/3 test files are not working. What's the problem?

**Comment by salmafg** [comment]
Testing verified.

**Comment by ghost** [comment]
close the story please
