### ISSUE TITLE
C5.S20/C5.S21 - As a guest, I can enter my data before playing the game/ As a guest, I can proceed with my signing up after playing the game

### ISSUE THREAD

**Issue by abulazm22** [MGhanem/smartsoft-13#359]
Success: as a guest, before playing the game, he should enter his country, gender, age and education level then proceed to play the game/ after each level, a prompt will be viewed to the guest to sign up as a gamer. If he accepted the request, he should be redirected to a page where he can enter his missing signup information and then proceed to confirm his account via a verification mail. The guest can skip the prompt to the next level if he won the previous level, or start a new game after a game over.
Failure: The guest will be prohibited from social connection, reporting, earning prizes and trophies/ validation checks
1)Research 
2)UML @Mirna-Yacout 
3)Implement @nohahesham 
4)Test @m0hamed 
5)Documentation @SalmaFG

**Comment by m0hamed** [comment]
the doctor said that we should use the date-picker to select dates. however I personally dont like it. I have sent the company an email to discuss it. once we have reached a decision we will see if you need to change your view or not

**Comment by m0hamed** [comment]
whenever the user enters wrong info the page refreshes and every thing he entered gets deleted it shouldnt do that

**Comment by salmafg** [comment]
Documentation verified.

**Comment by m0hamed** [comment]
please increase the size of the arabic text in the button. also the entire form is empty please make it smaller and center it on the page also the errors that are displayed are shifted to the right while their container is shifted to the left so they appear outside their container

**Comment by salmafg** [comment]
Documentation verified.

**Comment by nohahesham** [comment]
@Fattouh92 check comment

**Comment by nohahesham** [comment]
verified

**Comment by abulazm22** [comment]
@SalmaFG @m0hamed would you kindly review?

**Comment by m0hamed** [comment]
the text in the text box is too small in arabic. also the form should send data using post rather than get so that the url on top should not contain the user's pass word and not be too long

**Comment by abulazm22** [comment]
The form does send data using post of course and doesn't contain the password and what gets at the top are the errors. I have two methods one post one get. the post creates the gamer and performs validation but if I hav an error I send them to the get action in the params, I beleive There is no athoer way to do this. That explains the long URL

**Comment by abulazm22** [comment]
@m0hamed

**Comment by abulazm22** [comment]
Text box font is the same  in arabic and the URL is just fine and signing up happens by a post request and the password can't be accessed

**Comment by m0hamed** [comment]
if I am a guest and I signed up as a gamer I dont see anything that says that I have actually signed up. I should get a thank you notice. also you should set the should see tutorial column of the new user to false because he has already seen it when he signed up as a guest

**Comment by m0hamed** [comment]
This is the full game and should not say that this is only a part of the game in the notification. also a notification is not needed anyway at this point scince it is obvious what happened. a notification is only needed for the other form where you become a full member

**Comment by m0hamed** [comment]
also I said that he should not see the tutorial again after becoming a member

**Comment by abulazm22** [comment]
Ashraf he can't tweet or get prizes. So that's not the complete game plus the showtutorial gets the value of the guest gamer showtutorial so if you did press skip tutorial when guest it will not show when normal user but if you didn't it will be appear to you when gamer :D

**Comment by abulazm22** [comment]
I think zoheiry only set it for current_gamer not guest so I will check with him tomorrow

**Comment by m0hamed** [comment]
I am pretty sure I skipped tutorial and it came again when I signed up as a gamer. I will check again

**Comment by abulazm22** [comment]
Now I am sure that it is a problem from game. Will do tell him tomorrow

**Comment by abulazm22** [comment]
Yes but when you are a guest and press skip tutorial nothing happens for the column showtutorial. he has to set it to false. I think he only does it for current_gamer

**Comment by m0hamed** [comment]
ok change the flash notice to reflect that he cannot share his score and donot say you have a part of the game since he can play it all

**Comment by m0hamed** [comment]
verify
