### ISSUE TITLE
C5.S12: As a Gamer I should be able to report keywords/synonyms.

### ISSUE THREAD

**Issue by Khloud-Khalid** [MGhanem/smartsoft-13#360]
Success: in the voting page of the game, I should be able to view a link for reporting keyword/synonyms. Upon clicking the link, a modal box containing the words to be reported will appear, and upon checking the words and submitting a flash indicating the report was submitted should be viewed

Failure: user reported the keyword/synonym before.

UML @nourhanZ 
Scenario @KareemAliRahman 
Implementation @adamggg 
Documentation+Testing @zoheiry

**Comment by nourhanZ** [comment]
Just reference nourhan mohamed story in UML and then I will verify

**Comment by krmali** [comment]
@Khloud-Khalid, change the location of the button to the far left in the same row, and make it class danger instead of primary.

**Comment by adamggg** [comment]
@Khloud-Khalid code has been reopened =)

**Comment by krmali** [comment]
@Khloud-Khalid , scenario verified

**Comment by adamggg** [comment]
@Khloud-Khalid code verified =)

**Comment by adamggg** [comment]
What's left in this issue???

**Comment by Khloud-Khalid** [comment]
@adamggg nothing, just resolving conflicts with master.

**Comment by Khloud-Khalid** [comment]
@adamggg please merge since you're the last reviewer to verify. =)
