### ISSUE TITLE
C3S26 As a guest I can sign up with google

### ISSUE THREAD

**Issue by AmrARaouf** [MGhanem/smartsoft-13#361]
Success:
connects account through api, redirected to the sign up page with all his information readily filled in

Failure:
error reported by api

Tasks:
1- Research
2- Implementation @Omar-Hossam @karimngr 
3- Documentation @SalmaFG 
4- Testing @SalmaFG 
5- UML @Mirna-Yacout

**Comment by ghost** [comment]
@Mirna-Yacout  please fix the labels for the issue

**Comment by ghost** [comment]
fix the scenario after adding the activation as it is not working correctly

**Comment by AmrARaouf** [comment]
@karimngr please re check
