### ISSUE TITLE
C5.S19 - As a Gamer i should know how to play the game

### ISSUE THREAD

**Issue by zoheiry** [MGhanem/smartsoft-13#362]
Success: It is my first time playing, the game will be pause every now and then, and tool tips will appear telling me what should be done at this point of time

Failure: It is not my first time playing, i should not see the tutorial

Tasks:
1- Research
2- documentation @mostafahassaan 
3- implementation @adamggg @KareemAliRahman  
4- testing @mostafahassaan 
5- sequence diagram @Khloud-Khalid

**Comment by Khloud-Khalid** [comment]
@zoheiry why is the name of all the objects game.js?

**Comment by zoheiry** [comment]
because they are all in the same file, and whats written above is the file
 name, not necessarily and object

**Comment by mostafahassaan** [comment]
zozo, in your documentation, the convention is a "--" for empty, not an "none"

**Comment by mostafahassaan** [comment]
tests verified

**Comment by zoheiry** [comment]
we never agreed on javascript conventions

**Comment by mostafahassaan** [comment]
there's no reason why there should be a difference between javascript and ruby documentation. it's jsut a small change

**Comment by zoheiry** [comment]
okay, ill change it ;)

**Comment by zoheiry** [comment]
done, and pushed

**Comment by mostafahassaan** [comment]
good man :D

**Comment by mostafahassaan** [comment]
verified :)

**Comment by zoheiry** [comment]
Thank you sir :)

**Comment by Khloud-Khalid** [comment]
UML verified.

**Comment by krmali** [comment]
Zoheiry , you really did a great job, it looks fantastic, but I have some small comments:
1- in the popup of "تكوين الكلمات" change "جاهزة لتكوين" to  "جاهزة للتكوين".
2- in the popup of "ضغط علي حرف" change "كما ترون " to "كما تري".

another thing, do you save that a specific gamer has took the tutorial?, because it takes to long.
Great job.

**Comment by zoheiry** [comment]
Thank you ill change that, i didn't notice that at all, thanks, and yes
after the gamer wins the first level, a modal appears asking him if he
wants to see this tutorial again or not, try winning the 1st level and see
what happens, Enjoy ;)

**Comment by zoheiry** [comment]
fixed the translations you mentioned

**Comment by adamggg** [comment]
Code has been reopened =D

**Comment by krmali** [comment]
scenario verified

**Comment by zoheiry** [comment]
@adamggg i fixed your comment, could you please review again and merge?
