### ISSUE TITLE
C4.S15 - Non Functional Dependency, Autocomplete the keyword search live

### ISSUE THREAD

**Issue by NourhanMohamed** [MGhanem/smartsoft-13#364]
Success: 
Enter keyword in search box get list results as autocomplete. 

Failure: 
No words found so no autocomplete list

Tasks:
C4.S15.0    Implementation
C4.S15.1    Documentation
C4.S15.2    Sequence Diagrams
C4.S15.3    Research Autocomplete
C4.S15.4    unit tests

Reviewers:
Implementation: @adamggg 
Scenario: @m0hamed 
Documentation and Test: @mostafahassaan 
UML: @nourhanZ

**Comment by m0hamed** [comment]
Sorry but the autocomplete doesnt work in arabic. You can look at my pull request to see the changes I did to make it work. scenario reopened

**Comment by mostafahassaan** [comment]
please use the template stated below for documentation

# author:

  #   Mostafa Hassaan
  # description:
  #   function returns a hash with all keywords followed by a developer
  # params:
  #   gamer_id: id used to get the developer
  # success:
  #   returns a hash containing all keywords followed by the given developer
  # failure:
  #   returns empty hash if the developer doesn't follow any keywords

**Comment by NourhanMohamed** [comment]
please review again 
@mostafahassaan 
@adamggg

**Comment by mostafahassaan** [comment]
docs verified :)

**Comment by mostafahassaan** [comment]
can you please check again the tests? I'm getting 2 failures and I don't know thats a problem with my database wala your tests

1) SearchController GET search should get all keywords if no category specified
     Failure/Error: success, category = Category.add_category_to_database_if_not_exists("test")
     ActiveRecord::StatementInvalid:
       SQLite3::SQLException: no such column: categories.name: SELECT  "categories".\* FROM "categories"  WHERE "categories"."name" = 'test' LIMIT 1
2) SearchController GET search should get only keywords in category
     Failure/Error: success, category = Category.add_category_to_database_if_not_exists("test")
     ActiveRecord::StatementInvalid:
       SQLite3::SQLException: no such column: categories.name: SELECT  "categories".\* FROM "categories"  WHERE "categories"."name" = 'test' LIMIT 1

**Comment by NourhanMohamed** [comment]
These are not concerned with my story, these are ashraf's and the columns changed so this should be failing as u r getting

**Comment by mostafahassaan** [comment]
verified then :)

**Comment by mostafahassaan** [comment]
*test verified

**Comment by NourhanMohamed** [comment]
@m0hamed fixed the issues with the arabic view.. please review

**Comment by m0hamed** [comment]
sorry there is a problem
you need to send the categories list along with your keyword in you story
The categories search was working
are you using the same method or are you using a different method for the auto complete list
you should use the same method so that the search by categories work
you need to still have the previous view where the developer may see the words matching his category

**Comment by NourhanMohamed** [comment]
@m0hamed what did u decide about the categories search thingy? shall I modify anything regarding this issue?

**Comment by m0hamed** [comment]
wait till I talk to the doctor about it. just remind me to talk to her tomorrow

**Comment by NourhanMohamed** [comment]
@m0hamed what's your decision?

**Comment by m0hamed** [comment]
talked to the doctor and she said that we could remove the search by categories story. so I could review then I will reopen my story and remove it from the page.

**Comment by m0hamed** [comment]
make the text in the search box bigger. make it about 18px

**Comment by NourhanMohamed** [comment]
@m0hamed I fixed it .. please re-review =)

**Comment by m0hamed** [comment]
verified

**Comment by ghost** [comment]
if the story is done close it please
