### ISSUE TITLE
C5S14 - As an admin, I should be able to view all reports I recieved on keywords/synonyms

### ISSUE THREAD

**Issue by omar-mohyeldin** [MGhanem/smartsoft-13#365]
Success: after signing in and navigating to the admin panel, the admin can navigate to a tab that lists all the reported keywords/synonyms. If no reported keywords/synonyms are there, a message should be displayed
Failure: none
Tasks:
Implement function @nohahesham 
Implement  @karimngr 
testing @AmrARaouf 
UML @Mirna-Yacout 
Documentation

**Comment by nohahesham** [comment]
code verified
