### ISSUE TITLE
C5.S13 - As a Developer, I should be able to report keywords/synonyms

### ISSUE THREAD

**Issue by NourhanMohamed** [MGhanem/smartsoft-13#366]
Success: 
in the voting page of the game, I should be able to view a link for reporting keyword/synonyms. Upon clicking the link, a modal box containing the words to be reported will appear, and upon checking the words and submitting a flash indicating the report was submitted should be viewed

Failure:
user reported the keyword/synonym before

Tasks:
C5.S13.0    Unit tests
C5.S13.1    Implementation
C5.S13.2    Documentation
C5.S13.3    Sequence Diagrams

Reviewers:
Implementation: @adamggg 
Scenario: @m0hamed 
Documentation and tests: @mostafahassaan 
UML: @nourhanZ

**Comment by adamggg** [comment]
@NourhanMohamed check my comments on the files =)

**Comment by NourhanMohamed** [comment]
done
and as for the ar.yml file it is correctly displayed in the view regardless of how it is displayed in the yml file =)

**Comment by NourhanMohamed** [comment]
please re-review

**Comment by m0hamed** [comment]
when I click report where is the notification that says the report has been sent. Also the text in the modal shouldnt be "all the words in the page" but it should say that which words you would like to report. In english and arabic

**Comment by adamggg** [comment]
@NourhanMohamed Check my comments =)

**Comment by NourhanMohamed** [comment]
@adamggg check back

**Comment by NourhanMohamed** [comment]
@m0hamed you didn't change my label to re-open.. I'm gonna change it

**Comment by NourhanMohamed** [comment]
^ just because I search via labels for my re-opens so I need it changed =)

**Comment by adamggg** [comment]
@NourhanMohamed Code verified.

**Comment by NourhanMohamed** [comment]
@m0hamed any ideas where should I display the flash message? because I did my own flash message and I render it whenever I want, but I have no idea where to put it because if I added it at the top of the page the user has to scroll up to see it, since the report button is at the bottom of the page.

**Comment by mostafahassaan** [comment]
doc verified

**Comment by m0hamed** [comment]
you could show it using fixed coordinates on the top of the page.

if you set position to fixed and top and left to appropriate values it
should remain at the top of the page without scrolling. just make sure it
disapears after some time

**Comment by nourhanZ** [comment]
UML reopen:
1) The search view should have an activation box when the user clicks report button
2) the activation box of the search view should not be so long it should end by calling the controller and start once again when the return line comes back from the controller to the search view
3) I think the opt boxes that checks what the user will do should be on the time line of the search view instead of the actor as all checks and actions in response to user actions are handled by the view not the actor.

**Comment by mostafahassaan** [comment]
tests verified

**Comment by NourhanMohamed** [comment]
@nourhanZ I'll modify both ur 1st and 2nd comments, but as for the 3rd the opt boxes are user driven not view driven, It's either the user click something, or he clicks another and we used to represent the clicks on the actor timeline not the view. What do u think?

**Comment by NourhanMohamed** [comment]
@nourhanZ another thing! we used to end the activation box as the controller is invoked, but here I'm using ajax so everything is happening while the view is still there. Another thing is the activation box on the search view, why should it be there? nothing happens rather than the modal box flying in?

**Comment by NourhanMohamed** [comment]
@m0hamed please review again =)

**Comment by nourhanZ** [comment]
UML verified

**Comment by m0hamed** [comment]
I cannot review till we decide on where the button will go

**Comment by m0hamed** [comment]
please commit the latest code
the test in english should be report wrds on this page. and in arabic should be bal3' 3an kalemat fe hazehi al saf7a

**Comment by NourhanMohamed** [comment]
@m0hamed I changed the text a little bit, check it and inform me of changes =)

**Comment by NourhanMohamed** [comment]
@m0hamed wait I'm fixing something, don't verify now

**Comment by NourhanMohamed** [comment]
@m0hamed you can review now.. and try loading the page, shutting down the server and then submitting a report :D

**Comment by m0hamed** [comment]
are you sure you tested this because I get an exception when trying to create a report and your message says I lost my internet connection even though the server is running. the server log showed me this: 
NoMethodError (undefined method `text?' for nil:NilClass):
  app/models/report.rb:26:in`create_report'
  app/controllers/search_controller.rb:62:in `block in send_report'
  app/controllers/search_controller.rb:58:in`each'
  app/controllers/search_controller.rb:58:in `send_report'

**Comment by m0hamed** [comment]
also the message should be alot shorter. it should just say there was a problem and we cannot complete your request. you cannot be sure that the internet was cutoff. maybe an exception has occured like in this situation

**Comment by NourhanMohamed** [comment]
I ran rake db:migrate and fully tested it on my branch and I've got no errors O.o

**Comment by m0hamed** [comment]
hmm. ok let me do a reset and a populate

**Comment by m0hamed** [comment]
either way do the changes I asked.

**Comment by NourhanMohamed** [comment]
fixed translations

**Comment by NourhanMohamed** [comment]
I may tear out of happiness if this wasn't "scenario reopen"ed again!

**Comment by m0hamed** [comment]
please pull master onto your branch

**Comment by m0hamed** [comment]
verified

**Comment by NourhanMohamed** [comment]
I can't believe myself!! :D
@m0hamed pulled master and resolved conflicts.. please merge =)

**Comment by NourhanMohamed** [comment]
closing upon merge ...
