### ISSUE TITLE
C5S15, As an admin, I should be able to accept a report I recieved upon a keyword/synonym

### ISSUE THREAD

**Issue by omar-mohyeldin** [MGhanem/smartsoft-13#367]
success: The admin should be able to accept or reject a report using button in the report view. A subsequent email should be sent with feedback to the user that reported the keyword/synonyms. after signing in an navigating to the admin panel, the admin can
navigate to a tab that lists all the reported keywords/synonyms. If no
reported keywords/synonyms are there, a message should be displayed
failure: none
Tasks:
Implement function @nohahesham 
Implement UI @karimngr 
testing @AmrARaouf 
UML @Mirna-Yacout 
Documentation

**Comment by nohahesham** [comment]
code verified

**Comment by ghost** [comment]
verified

**Comment by nohahesham** [comment]
verified
