### ISSUE TITLE
C5.S07 - As a Developer, I should be able to view recommended words according to my project category

### ISSUE THREAD

**Issue by salmafg** [MGhanem/smartsoft-13#370]
Success:
When user clicks view recommended words button, he should be able to view a list of the recommended keywords with the highest voted synonym filtered by the project criteria. He should be able to check several words using checkboxes and finally add them to his project. Free users are not allowed to use this feature.

Failure:
None of the keywords are there in the category chosen, and an appropriate message should be displayed. Also if no synonyms match the project criteria, the most voted synonym generally should be displayed, telling the user that this synonym doesn't match his criteria.

Tasks:
1- Research
2- Implementation @nohahesham 
3- Documentation @AmrARaouf  
4- Testing @AmrARaouf  
5- UML @Fattouh92 
6- Scenario @m0hamed

**Comment by m0hamed** [comment]
the select list of synonyms should either be enabled form the begining or not be visible unless he checks the box. also keywords with no synonyms should not be shown because he cannot add them anyway and there should be a back to the project page link

**Comment by salmafg** [comment]
@m0hamed I'm not convinced about the first point. Why would I want to hide
it or leave it enabled? It's better that way.
Also, I already do not show keywords without synonyms. But I will add a
back link to the projects page.

**Comment by salmafg** [comment]
@m0hamed 
@AmrARaouf
@nohahesham 
Please review

**Comment by salmafg** [comment]
@Fattouh92 Please review

**Comment by m0hamed** [comment]
every-time I go to the recommended words page I get you donot have any recommended words. how do I get recommended words.

**Comment by m0hamed** [comment]
when I press back it takes me to the projects list page rather than to my project

**Comment by m0hamed** [comment]
please tell me what criteria do I set the project in order to get recommended words. also please add more words to the populate file so that the doctor can get words in the demo.

**Comment by m0hamed** [comment]
I should get all words in a category if I don't have them in my project. the synoyms are then ordered not filtered according to votes so even if no votes are offered using the project criteria I should still be shown but at the bottom of the synonym list.

**Comment by salmafg** [comment]
@m0hamed By setting the keyword.categories to the same category as the project.

**Comment by salmafg** [comment]
@m0hamed I am not filtering according to votes.

**Comment by salmafg** [comment]
@m0hamed Regarding the disabled dropdown, I think I figured why you were confused. The table-hover made the entire row the same color as the disabled dropdown so it wasn't obvious. I removed the hover thing. It should be clear now.

**Comment by m0hamed** [comment]
didnt we agree yesterday that it should appear only when selected

**Comment by salmafg** [comment]
@m0hamed It would look confusing to the user opening a link and finding keywords and an empty column. How would he know that the synonyms will appear when the checkbox is checked?

**Comment by salmafg** [comment]
@Fattouh92 @m0hamed

**Comment by salmafg** [comment]
@AmrARaouf

**Comment by m0hamed** [comment]
verified

**Comment by salmafg** [comment]
@nohahesham @AmrARaouf

**Comment by nohahesham** [comment]
verified
