### ISSUE TITLE
C5.S25 - As a guest I can sign up with twitter

### ISSUE THREAD

**Issue by Mirna-Yacout** [MGhanem/smartsoft-13#371]
success: connects account through api, redirected to the sign up page with all his information readily filled in
failure: error reported by the api

Tasks:
research
documentation & testing @AmrARaouf 
UML @Fattouh92 
scenario @karimngr 
code @Omar-Hossam

**Comment by ghost** [comment]
@Mirna-Yacout  please fix the labels for this issue

**Comment by Mirna-Yacout** [comment]
@karimngr what do u mean?

**Comment by ghost** [comment]
verified
