### ISSUE TITLE
C5.S06 - As a Gamer, I should be able to view a log of my votes in my profile tab

### ISSUE THREAD

**Issue by nourhanZ** [MGhanem/smartsoft-13#372]
Success: 
When the gamer navigates to their profile tab, he/she should be able to view a list of the votes they gave.
Failure: 
If the gamer never votes before, a message should be displayed to the gamer indicating this.

Reviewers:
Documentation/Test Reviewer @mostafahassaan 
UML/Design Reviewer @Khloud-Khalid 
Implementation Reviewer @NourhanMohamed 
Scenario Reviewer @m0hamed

Tasks:
C5.S06.1 - Unit Tests 
C5.S06.2 - Implementation 
C5.S06.3 - User Interface 
C5.S06.4 - UMLs 
C5.S06.5 - Documentation

**Comment by nourhanZ** [comment]
@m0hamed @NourhanMohamed @mostafahassaan please review :)

**Comment by nourhanZ** [comment]
@Khloud-Khalid please review :)

**Comment by nourhanZ** [comment]
@Khloud-Khalid I changed a small thing, please review :)

**Comment by mostafahassaan** [comment]
Nourhan! please use the convention with all your docs
  # author:
  #   Mostafa Hassaan
  # description:
  #   function returns a hash with all keywords followed by a developer
  # params:
  #   gamer_id: id used to get the developer
  # success:
  #   returns a hash containing all keywords followed by the given developer
  # failure:
  #   returns empty hash if the developer doesn't follow any keywords

**Comment by mostafahassaan** [comment]
verified :)

**Comment by m0hamed** [comment]
donot call it profile call it vote history

**Comment by nourhanZ** [comment]
@m0hamed fixed comments please review again :)
@mostafahassaan fixed docs please review again :)

**Comment by mostafahassaan** [comment]
very small issue with documentation, please check again :)

**Comment by nourhanZ** [comment]
@mostafahassaan please review again :)

**Comment by m0hamed** [comment]
please add a margin to the back button and fix it because sometimes it doesnt work.

**Comment by Khloud-Khalid** [comment]
verified :)

**Comment by NourhanMohamed** [comment]
check pull request comments

**Comment by mostafahassaan** [comment]
docs verified

**Comment by nourhanZ** [comment]
@m0hamed I fixed the scenario comments please review again :)

**Comment by nourhanZ** [comment]
@m0hamed I changed it again please review :)

**Comment by m0hamed** [comment]
call it back to game and thats it. I dont need back I just need back to game

**Comment by nourhanZ** [comment]
@NourhanMohamed @m0hamed please review :)

**Comment by nourhanZ** [comment]
@NourhanMohamed @m0hamed please review :)

**Comment by NourhanMohamed** [comment]
almost verified.. just one comment
Check pull request comment

**Comment by NourhanMohamed** [comment]
code verified

**Comment by m0hamed** [comment]
verified

**Comment by m0hamed** [comment]
verified

**Comment by mostafahassaan** [comment]
verfied
