### ISSUE TITLE
C5.S22-Flash messages should disappear after 5 secs

### ISSUE THREAD

**Issue by nohahesham** [MGhanem/smartsoft-13#373]
success:none
failure:none

Tasks:
1-implementation
2-documentation
@SalmaFG 
@Fattouh92 
@m0hamed 
@Omar-Hossam

**Comment by nohahesham** [comment]
@m0hamed  it doesnt move the page:)

**Comment by m0hamed** [comment]
where is the pull request

**Comment by m0hamed** [comment]
the flash should be visible for a few seconds before it starts disappearing. also errors should not fade out

**Comment by nohahesham** [comment]
okii

**Comment by m0hamed** [comment]
verified
