### ISSUE TITLE
C5.S16-As a gamer,I should be able to change the game tab I'm currently in

### ISSUE THREAD

**Issue by nohahesham** [MGhanem/smartsoft-13#374]
success:users will have an options button at the top right corner/ top left corner according to the locale. Upon clicking a drop down with the tabs will be displayed. Upon clicking the tab the tab name will be displayed next to the tabs button.
failure:none
Tasks:
1-implementation
2-documentation
@SalmaFG 
@Omar-Hossam 
@m0hamed 
@Fattouh92

**Comment by m0hamed** [comment]
this should be within the game box not ontop. it needs to be much smaller. and the text inside needs to be bigger in arabic

**Comment by m0hamed** [comment]
@adamggg since we didnt do back because we would have this instead. please give us your input

**Comment by m0hamed** [comment]
there should also be a tab for the game itself so the user can go to the game at any time.

**Comment by adamggg** [comment]
I think there should be a button which sends him back just to the main page
where he/she chooses the language? What do you think?

**Comment by nohahesham** [comment]
@m0hamed

**Comment by nohahesham** [comment]
@a
