### ISSUE TITLE
C3.S17-As a developer,I Should be able to remove a project shared with me

### ISSUE THREAD

**Issue by nohahesham** [MGhanem/smartsoft-13#375]
success:The project will be removed, not deleted.
failure:none
Tasks:
1-Implementation
2-Documantation
3-Testing
4-Research
5-UML
@SalmaFG 
@Fattouh92 
@m0hamed 
@Omar-Hossam

**Comment by m0hamed** [comment]
please make sure to pull master because the homepage is giving an exception on this branch

**Comment by m0hamed** [comment]
also there are mising translations in the share page. I have sent an email in the mailing list you can see the list please fix them

**Comment by nohahesham** [comment]
@m0hamed 
@SalmaFG

**Comment by nohahesham** [comment]
@m0hamed 
@SalmaFG 
@Fattouh92

**Comment by m0hamed** [comment]
all success messages should be green. also who did the list projects shared with me story

**Comment by nohahesham** [comment]
what list?? its me

**Comment by nohahesham** [comment]
@m0hamed

**Comment by m0hamed** [comment]
first of all the list of shared projects doesnt show category. also the button of the delete should be red and should show a modal asking him to confirm deletion

**Comment by m0hamed** [comment]
donot forget to change the labels

**Comment by nohahesham** [comment]
yes when salma finishes the category and it gets merged i will pull it, i did that to avoid the errors untill she is done

**Comment by nohahesham** [comment]
cause the category column is deleted @m0hamed

**Comment by m0hamed** [comment]
ah nice :)

anyway just fix the last comment and that should probably be it

**Comment by nohahesham** [comment]
and also the index is still gonna be fixed

**Comment by nohahesham** [comment]
okkk:)

**Comment by nohahesham** [comment]
@m0hamed plz review

**Comment by m0hamed** [comment]
the text should not say delete or mas7 as that emplies you are actually deleting the project. it should be in btn warning and should be el3'a2 al eshterak or unshare. and the icon should be changed to a more apropriate one

**Comment by nohahesham** [comment]
what do you want the text to be??

**Comment by nohahesham** [comment]
@m0hamed

**Comment by m0hamed** [comment]
I said el3'a2 al eshterak or unshare I dont know about the icon you can use the x this time since we are not deleting we are removing

**Comment by m0hamed** [comment]
the buttons should all be yellow warning and the text in the modal should expalin that he will not be able to view that project again

**Comment by nohahesham** [comment]
@Fattouh92 plz review uml

**Comment by nohahesham** [comment]
@m0hamed plzz review again

**Comment by m0hamed** [comment]
sorry about this I was talking to the team and they told me that the red button was better. you can change it back if you want it. Also in the project list page the text in the unshare button in arabic is very small please increase its size and also increase the size of the edit button next to it, also the fontsize should only increase in the arabic only not in english in the modal as well as in the listing. also the text of the modal should not be bold and the title of the unshare modal should be "remove project from shared projects"

**Comment by m0hamed** [comment]
there is an h5 around the text in the modal that makes it bold just remove it or change it to span instead

**Comment by nohahesham** [comment]
u mean the modal title? @m0hamed

**Comment by nohahesham** [comment]
@m0hamed 
@SalmaFG  plz revieww

**Comment by nohahesham** [comment]
i modified it again @m0hamed

**Comment by nohahesham** [comment]
@SalmaFG

**Comment by nohahesham** [comment]
@Fattouh92

**Comment by m0hamed** [comment]
please pull master on your branch

**Comment by ghost** [comment]
if the story is done please close it

**Comment by nohahesham** [comment]
@m0hamed

**Comment by m0hamed** [comment]
you still have merge conflict markers in one of the files

**Comment by nohahesham** [comment]
@m0hamed

**Comment by nohahesham** [comment]
i didnt notice :D

**Comment by nohahesham** [comment]
i fixed it

**Comment by m0hamed** [comment]
there is still another file that has merge markers. please check the pull request to find them all

**Comment by m0hamed** [comment]
sorry I was looking at an old branch
verified

**Comment by nohahesham** [comment]
@m0hamed  i searched every file in the pull request and the project but there is nth

**Comment by nohahesham** [comment]
okaay:D

**Comment by nohahesham** [comment]
plz merge it @m0hamed

**Comment by m0hamed** [comment]
actually no there is still a merge marker in bootstrap_overrides

**Comment by nohahesham** [comment]
tab ha check now

**Comment by nohahesham** [comment]
@m0hamed i fixed it

**Comment by AmrARaouf** [comment]
sorry closed by mistake
