### ISSUE TITLE
title 

### ISSUE THREAD

**Issue by zoheiry** [MGhanem/smartsoft-13#545]
issue body

**Comment by adamggg** [comment]
Eh? Lol

**Comment by adamggg** [comment]
Hahaha was showing the students something xD

Ali El Zoheiry
Takeoff Apps, Co-Founder
www.takeoffapps.com | zoheiry@takeoffapps.com

**Comment by adamggg** [comment]
Haha alright =D

On Sun, Mar 8, 2015 at 2:35 PM, Ali El Zoheiry ali.elzoheiry@gmail.com
wrote:

> Hahaha was showing the students something xD
> 
> Ali El Zoheiry
> Takeoff Apps, Co-Founder
> www.takeoffapps.com | zoheiry@takeoffapps.com
> On Mar 8, 2015 12:57 PM, "Adam Ghanem" ghanem.adam@gmail.com wrote:
> 
> > Eh? Lol
> > 
> > Sent from my iPhone
> > 
> > On Mar 8, 2015, at 12:53, zoheiry notifications@github.com wrote:
> > 
> > Closed #545 https://github.com/MGhanem/smartsoft-13/issues/545.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/MGhanem/smartsoft-13/issues/545#event-248133153.

## 

Adam Ghanem
Takeoff Apps, Co-Founder
www.takeoffapps.com | adam@takeoffapps.com
