### ISSUE TITLE
C4.S01 - As a Developer, I can search for keywords in english and arabic

### ISSUE THREAD

**Issue by NourhanMohamed** [MGhanem/smartsoft-13#74]
Success: View the list of keywords that are similar to the word typed in the search textbox in the database
Failure: No keyword found in database. Suggest to add to the database
Tasks: 
1. Sequence Diagram @nourhanZ 
2. Documentation @mostafahassaan 
3. Researching the topic
4. Implementation @m0hamed 
5. User Interface

**Comment by m0hamed** [comment]
The pull request cannot be merged automatically.

**Comment by nourhanZ** [comment]
1) please can you change the title of the sequence diagram to have the following format:
Diagram type Diagram name [(parameter type:parameter Name)] : [return value type] 
as this will make things easier later if we want to reference one of the diagrams in another diagram -- we can also keep the story number to make things easier
2) please add colon between parameter type and parameter name ex string:name
3) add return type of the method ex search(string:word):string
4) add the part of the integration between you and the story S14

**Comment by mostafahassaan** [comment]
please check docs

**Comment by NourhanMohamed** [comment]
@m0hamed @mostafahassaan updated your comments regarding code and documentation issues.. Please review again :octocat:

**Comment by m0hamed** [comment]
howa ezzay el doc pending we reopen fe nafs el wa2t

**Comment by m0hamed** [comment]
howa fadel 7ettah soghayarah we ba3deen yeb2a verified

**Comment by NourhanMohamed** [comment]
@m0hamed updated according to your comments, please review

**Comment by NourhanMohamed** [comment]
@mostafahassaan eh wad3 el documentation? 3'ayar el label if u reviewed :)

**Comment by NourhanMohamed** [comment]
@nourhanZ I updated the sd, please review :)

**Comment by NourhanMohamed** [comment]
@m0hamed which branch of yours should I pull to update the deletion of unncessary files? S11 or S14?

**Comment by m0hamed** [comment]
either, choose whichever one you pulled before

**Comment by NourhanMohamed** [comment]
@m0hamed please review.. ya mosahel :D

**Comment by m0hamed** [comment]
an extra space we teb2a verified

**Comment by mostafahassaan** [comment]
Docs verified! ma3lesh el noom kan 7lw awi today :sleeping:

**Comment by m0hamed** [comment]
yallah verified :+1:

**Comment by NourhanMohamed** [comment]
@m0hamed added the space! :D please review

**Comment by NourhanMohamed** [comment]
el7amdullaaaaaah :D zwedtelak el space bardo :D

**Comment by NourhanMohamed** [comment]
hahahah @mostafahassaan m3lsh I removed a line from documentation in the keyword controller method suggest_add.. please review again

**Comment by mostafahassaan** [comment]
@NourhanMohamed  howa enti shelti descriptions wala ana kont mesa2at kol da? check again :D

**Comment by NourhanMohamed** [comment]
updated documentation description field @mostafahassaan "enta kunt msa2at aywa :P"

**Comment by mostafahassaan** [comment]
allah yenwar 7aga 2alaga walahy

**Comment by nourhanZ** [comment]
Verified

**Comment by NourhanMohamed** [comment]
Allah Akbar! :D 
@m0hamed @nourhanZ @mostafahassaan request for merge :dancers:

**Comment by mostafahassaan** [comment]
merged :D

**Comment by NourhanMohamed** [comment]
Wooooooooohooooooooo :fireworks:

**Comment by NourhanMohamed** [comment]
@adamggg @m0hamed @mostafahassaan @nourhanZ please review

**Comment by nourhanZ** [comment]
1) In the UML you invoked the search method while it's the search_keywords method so please change this in the UML
2) The alt box in the Keyword model can just be an opt box since the rest of the code is not written in else part 
3) The return line from the Keyword model to the Search controller should be @similar_keywords instead of relevant_first_list since this is the variable name in the Search controller

**Comment by mostafahassaan** [comment]
tests verified

**Comment by mostafahassaan** [comment]
You are using the old documentation template, please update them :)
