### ISSUE TITLE
C3.S15 As a developer, I should be able to view my projects.

### ISSUE THREAD

**Issue by abulazm22** [MGhanem/smartsoft-13#75]
Success: A page listing all the projects ordered descendingly by the creation date
Failure: none
1.Research 
2.Documentation @SalmaFG 
3.UML @Mirna-Yacout  
4.Retrieve projects from the database and loop on them and return only the ones where the creator id of the project matches the current id @nohahesham 
5.Add bootstrap and edit the view using CSS @m0hamed

**Comment by nourhanZ** [comment]
1) Please can you change the title of the sequence diagram to have the following format:
Diagram type Diagram name [(parameter type:parameter Name)] : [return value type] 
as this will make things easier later if we want to reference one of the diagrams in another diagram -- please also add the story number in the title to make things easier
2) Please try to make the activation boxes not too long as they represent the time  of execution of method starting with invoking it till the return or response
3)the ".where(:developer => developer.id)" part in the UML is not exactly like the part in the code ".where(developer_id=>developer.id)"  so please look at this part and fix this little problem :)

**Comment by nourhanZ** [comment]
UML - Verified

**Comment by NourhanMohamed** [comment]
Close the issue ya gama3a talama merged
