### ISSUE TITLE
C4.F7 - Provide a list of words with unapproved suggested synonyms

### ISSUE THREAD

**Issue by mostafahassaan** [MGhanem/smartsoft-13#76]
Success:
Input: None.
Output: returns a lists of words with unapproved suggested synonyms.

Failure: returns an empty list if there are no unapproved suggested synonym

Tasks:
C4.F7.1 - Sequence Diagram @nourhanZ 
C4.F7.2 - Research list relations 
C4.F7.3 - Documentation @SalmaFG 
C4.F7.4 - Implementation @NourhanMohamed @m0hamed

**Comment by m0hamed** [comment]
LGTM I left the code pending left so that @NourhanMohamed can review

**Comment by m0hamed** [comment]
According to the newly found code guidelines in order to create class methods you use class << self rather than self.

here is a link explaining how to use class << self
http://www.railstips.org/blog/archives/2009/05/11/class-and-instance-methods-in-ruby/

**Comment by nourhanZ** [comment]
1) please can you change the title of the sequence diagram to have the following format:
Diagram type Diagram name [(parameter type:parameter Name)] : [return value type] 
as this will make things easier later if we want to reference one of the diagrams in another diagram -- and please also add the story number to make things easier
2) Reconsider the join part in the UML, I think it's not 100% correct

**Comment by NourhanMohamed** [comment]
Just be sure that each line doesn't exceed 80 characters. Other than that everything is fine :+1:

**Comment by mostafahassaan** [comment]
@nourhanZ

**Comment by nourhanZ** [comment]
Everything is fine but small issues may change in sprint 1 but till now it's good :+1:

**Comment by mostafahassaan** [comment]
@SalmaFG the vote model is not my code, I needed it to finish my work. Please only review code in Keyword

**Comment by m0hamed** [comment]
then pull the branch that has that code to fix the documentation ya mostafa

**Comment by mostafahassaan** [comment]
Done, @m0hamed please merge wenaby! :D

**Comment by m0hamed** [comment]
you have two open pull request close one fix the aother because it cannot be automatically merged

**Comment by mostafahassaan** [comment]
Okay I closed one :) It can now be merge, I fixed conflicts
@m0hamed @NourhanMohamed @nourhanZ

**Comment by m0hamed** [comment]
fixed
