### ISSUE TITLE
C3.S07 - As a Developer, I should be able to add a new project

### ISSUE THREAD

**Issue by salmafg** [MGhanem/smartsoft-13#77]
Success:
Through the projects page, the developer can click a button to add a new project that opens a form with the project description. Where he can choose one or more project categories (banking, education, medical.. other..etc), specify the age target through a textbox and specify whether the project uses formal or slang words. When all data are entered correctly, it should view the project.

Failure:
If the developer is a free developer and has exceeded 1 projects, an error will appear: "You have reached the max number of projects,  subscribe as a premium user". If some data are missing in the form, it will highlight them.

Tasks:
1. Research on validations
2. Documentation @AmrARaouf 
3. UML @Fattouh92 
4. Implementation @nohahesham 
5. Handling input errors
6. CSS & Bootstrap
7. Tests @AmrARaouf 
8. Scenario @m0hamed

**Comment by NourhanMohamed** [comment]
Remove the Status-inProgress label please :)

**Comment by mostafahassaan** [comment]
Please check comments on documentation in the files changed section :)

**Comment by mostafahassaan** [comment]
verified

**Comment by m0hamed** [comment]
please change the labels next time. Your page throws an exception. and the pull request is not able to be merged automatically. If you donot update your labels I will not review you issue next time

**Comment by salmafg** [comment]
@m0hamed Please check now.

**Comment by m0hamed** [comment]
still throws exceptions, please make sure it doesnt show exceptions before asking me to review. also it still cant be merged automatically on master

**Comment by salmafg** [comment]
@m0hamed Why U no reopen the issue?!
Check now!

**Comment by m0hamed** [comment]
why is the formal_slang still called el no3. change it to something more descriptive. The success message for creating project should be green. and the project description is not saved

**Comment by salmafg** [comment]
@m0hamed Fixed all problems.

**Comment by m0hamed** [comment]
this is the same pull request so you should see the comments on the other issue

**Comment by m0hamed** [comment]
please leave this as reopened till we review the other one so that I dont have to change the tags on it every time.

**Comment by salmafg** [comment]
@m0hamed Please review.

**Comment by m0hamed** [comment]
verified
