### ISSUE TITLE
C3.S20-As a Developer,I Should be able to delete my project

### ISSUE THREAD

**Issue by nohahesham** [MGhanem/smartsoft-13#78]
success:The project can be deleted from its page or from the "all projects" page
Failure:As a free user, I cannot delete my project
Tasks:
1-Research
2-Documentation @SalmaFG 
3-Implementing the function @Omar-Hossam 
4-UML @Fattouh92

**Comment by NourhanMohamed** [comment]
Remove the Status-inProgress label please
N.B I still didn't review the code

**Comment by NourhanMohamed** [comment]
Review the changes on issue #95 and correct them

**Comment by m0hamed** [comment]
please change the labels correctly
also please tag the pull request with the issue number

**Comment by m0hamed** [comment]
delete the useless umls, and the useless index view
move the migration into its own branch and let me review it

**Comment by nohahesham** [comment]
@m0hamed 
@NourhanMohamed

**Comment by m0hamed** [comment]
This allows me to delete projects that donot belong to me. Make sure that only the owner can delete the project.

**Comment by m0hamed** [comment]
Also no feedback is given when it the project is deleted.

**Comment by nohahesham** [comment]
@m0hamed 
comments done

**Comment by m0hamed** [comment]
for the last time, change the labels Noha

**Comment by m0hamed** [comment]
the pull request is not mergable on master can you please pull it so I can test on the latest code

**Comment by m0hamed** [comment]
@nohahesham can you please merge master.

**Comment by m0hamed** [comment]
All feedback should be green if successful

**Comment by m0hamed** [comment]
sorry I closed this by mistake

**Comment by nohahesham** [comment]
@m0hamed plz review

**Comment by m0hamed** [comment]
the delete button in the project index page should be red and should have a some space between it and the edit button. also we said we will show confirmation box before deleting anthing. you should use the bootstrap modal to ask the user for confirmation

**Comment by m0hamed** [comment]
please arabize the modal dialog for confirmation

**Comment by nohahesham** [comment]
@m0hamed

**Comment by m0hamed** [comment]
use the trash icon with the delete button rather than the x.

**Comment by nohahesham** [comment]
@m0hamed done:)

**Comment by m0hamed** [comment]
verified

**Comment by adamggg** [comment]
Close this issue if it has been merged!

**Comment by AmrARaouf** [comment]
closed by mistake
