### ISSUE TITLE
C4.F8 - Provide the most voted synonym (synonym with highest votes)

### ISSUE THREAD

**Issue by mostafahassaan** [MGhanem/smartsoft-13#79]
Success: 
Input: Word.
Output: Returns most voted Synonym.

Failure:  Returns NULL if Word has no synonyms or no votes on synonyms.

Tasks: 
C4.F8.1 - Sequence Diagram @nourhanZ 
C4.F8.2 - Research 
C4.F8.3 - Documentaion @SalmaFG 
C4.F8.4 - Implementaion @NourhanMohamed @m0hamed

**Comment by m0hamed** [comment]
Yalla bessala 3alnaby awel reopen. Please use a more elegant way for finding the keyword with the maximum votes. I am closing the pull request. Please resubmit @mostafahassaan

**Comment by mostafahassaan** [comment]
Abo ashraf, I've been looking for a more elegant way ba2aly yomeen. That was a last resort.

**Comment by NourhanMohamed** [comment]
Howa el pull request closed leeh ya captain??

**Comment by NourhanMohamed** [comment]
@m0hamed I re-opened the pull request for him.. What I understood is that we don't close the pull request, we just update tags on the issue and comment.. Update me law ana mesh fahma
@mostafahassaan check same thingy of max 80 characters per line, and class << self.. I added comments over the pull request

**Comment by nourhanZ** [comment]
1) Please can you change the title of the sequence diagram to have the following format:
Diagram type Diagram name [(parameter type:parameter Name)] : [return value type] 
as this will make things easier later if we want to reference one of the diagrams in another diagram -- Please also add the story number to make things easier
2) In the methods with parameters add the parameter type before the parameter name separated with : and also add the return value type of the method after the method and also separated with : 
ex: highest_voted_synonyms(string : word ) :string
3) The loop part and the if part in the code isn't represented correctly in the UML, They must be represented using alt, opt or loop combined fragments which are the standard ways to represent them in UML.

**Comment by mostafahassaan** [comment]
@SalmaFG the vote model is not my code, I needed it to finish my work. Please only review code in Keyword and Synonym

**Comment by mostafahassaan** [comment]
@nourhanZ @m0hamed @NourhanMohamed Please review :D branch is ready to be merged

**Comment by NourhanMohamed** [comment]
check comments on the pull request

**Comment by mostafahassaan** [comment]
review again please :) @NourhanMohamed @m0hamed

**Comment by mostafahassaan** [comment]
@m0hamed fixed indentaion

**Comment by mostafahassaan** [comment]
whats wrong with the code tayeb?

**Comment by mostafahassaan** [comment]
we fein @nourhanZ abl maldenya te3ok conflicts

**Comment by NourhanMohamed** [comment]
check the comments on the pull request

**Comment by nourhanZ** [comment]
1) Mostafa change the (Keyword:word) on the first arrow because its ambiguous which one is the type and which one is the parameter name

**Comment by m0hamed** [comment]
you may use max or max_by and give them a block, Here is a the api link about them
http://ruby-doc.org/core-2.0/Enumerable.html#method-i-max

**Comment by NourhanMohamed** [comment]
@mostafahassaan enta nawy t5alas enharda wala eh wad3ak ??

**Comment by mostafahassaan** [comment]
please review :) @nourhanZ @NourhanMohamed @m0hamed

**Comment by m0hamed** [comment]
you messed up with the merge conflicts please correct the code

**Comment by mostafahassaan** [comment]
review again please

**Comment by NourhanMohamed** [comment]
did u push ur code? ana 3ande el files zay mahya

**Comment by m0hamed** [comment]
eb2a 3'ayar el labels

**Comment by mostafahassaan** [comment]
@m0hamed @nourhanZ @NourhanMohamed Pushed 3'alat we ma2a5adesh baly, check again
yarab!

**Comment by NourhanMohamed** [comment]
@mostafahassaan hanet kam space w t5alas yalla

**Comment by mostafahassaan** [comment]
wenabi give me good news

**Comment by mostafahassaan** [comment]
@m0hamed @NourhanMohamed

**Comment by m0hamed** [comment]
sala7 el code

**Comment by mostafahassaan** [comment]
5alas?
