### ISSUE TITLE
C1.S08 - A gamer/gamer(developer), I should be able to signin with my gamer account

### ISSUE THREAD

**Issue by adamggg** [MGhanem/smartsoft-13#80]
Success: Click on the Sign in button, a drop down menu appears where the user enters a username and password, if they are valid he will be redirected to the game

Failure: invalid username or password, the page is reloaded and the user is notified that he entered an invalid username or password

@KareemAliRahman 
@zoheiry 
@Khloud-Khalid 
@NourhanMohamed

**Comment by krmali** [comment]
Your coding styles and implementation are just fine.

**Comment by NourhanMohamed** [comment]
Close the issue ya gama3a talama merged

**Comment by NourhanMohamed** [comment]
check pull request comments :)

**Comment by adamggg** [comment]
@Khloud-Khalid 
@KareemAliRahman 
@NourhanMohamed 
@zoheiry 
Please review :smile:

**Comment by Khloud-Khalid** [comment]
@adamggg 

do both the 'sign_in(Gamer)' and data validation actions start at the same time? if not, the arrows shouldn't be on the same line.

**Comment by zoheiry** [comment]
Tests are all good, but please check the documentations comments

**Comment by Khloud-Khalid** [comment]
verified

**Comment by zoheiry** [comment]
Docs look good, verified

**Comment by NourhanMohamed** [comment]
check pull request comments

**Comment by NourhanMohamed** [comment]
code verified (Y)
