### ISSUE TITLE
C4.F05 - Function, record the approval of a certain synonym by the admin

### ISSUE THREAD

**Issue by Mirna-Yacout** [MGhanem/smartsoft-13#81]
success: takes the synonym_id and sets the is_approved field to 1 then returns true if the synonym was found and the approval is done.
failure: returns false in case the synonym doesn't exist in the database.

Tasks:
0. Research
1. Documentation @AmrARaouf 
2. Sequence Diagram @Khloud-Khalid 
3. search and approve the synonym in the database @karimngr @Omar-Hossam

**Comment by m0hamed** [comment]
your pull request caused issues in master. I am reopening this story. Please add me as a reviewer

**Comment by m0hamed** [comment]
please move your method to after the validations
rename the variables from sid to something more descriptive
no brackets are required after the if statement

**Comment by Mirna-Yacout** [comment]
@m0hamed how about now?

**Comment by m0hamed** [comment]
look at the comments

**Comment by m0hamed** [comment]
works for me

**Comment by m0hamed** [comment]
@karimngr approve yabney we merge
