### ISSUE TITLE
C1S20 - As an admin I should be able to populate the database by importing a csv file

### ISSUE THREAD

**Issue by AmrARaouf** [MGhanem/smartsoft-13#82]
Success: Click on the update database button and choose the method of insertion to be CSV, and start importing my CSV file.

Failure: Not an admin i wont be able to see the update database  button, or if the word i am trying to enter already exists then i am notified with an option to cancel insertion of that word, or just add my new translations to the already existing word.

Tasks:
1- ruby research on how to to manipulate a csv
2- button that imports .txt file @karimngr @Omar-Hossam 
3- parsing the csv string
4- inserting the words into the database
5- document the function @zoheiry 
6- design UML @Mirna-Yacout

**Comment by zoheiry** [comment]
@AmrARaouf please add the author to your documentations, and the description tag is missing in some of them
