### ISSUE TITLE
C4F3 - feature, Record suggested synonym for a given word

### ISSUE THREAD

**Issue by omar-mohyeldin** [MGhanem/smartsoft-13#83]
success: Output is boolean -- this method returns true if the vote has been recorded.
failure: returns false if word doesnt exist

Tasks:
Research feature implementation using ruby
implement feature adding synonym to database pointing to its' word, and returning a boolean value @karimngr 
create feature's documentation @AmrARaouf 
create feature's UML diagram @Mirna-Yacout

**Comment by NourhanMohamed** [comment]
Close the issue ya gama3a

**Comment by ghost** [comment]
reopened for sprint1

**Comment by ghost** [comment]
@Omar-Hossam  reopened to fix format and for scenario review

**Comment by ghost** [comment]
way to go @Omar-Hossam  :+1: keep it up

**Comment by m0hamed** [comment]
Your code is not working and shouldnt have been verified. @karimngr you should do a better job as a reviewer. I am reopening this issue till you fix your code.

An exception is thrown in anything that access the synonym model
