### ISSUE TITLE
C3.S03: As a Developer I should be able to continue registration.

### ISSUE THREAD

**Issue by Khloud-Khalid** [MGhanem/smartsoft-13#85]
Success: Has to be logged in as a Gamer and then registers as a developer to proceed with stages 3 (Subscription model) and 4 (Payments).
Failure: Some required data are missing/invalid. Page reloads highlighting missing fields. Also if the user is already registered.
UML @nourhanZ 
Scenario @KareemAliRahman 
Implementation @adamggg 
Documentation+Testing @zoheiry

**Comment by krmali** [comment]
@Khloud-Khalid Khloud you need to:
1- render and redirect to other pages instead of only make a notice.
2- Add another validation for the gamer_id in the Developer table.
3- it is preferred to use before_filter in the controllers , instead of making sure in each method.

**Comment by adamggg** [comment]
@Khloud-Khalid, code reopened. Check the comments I have left on the code in the pull request.

**Comment by Mirna-Yacout** [comment]
@Khloud-Khalid UML reopened

**Comment by adamggg** [comment]
I have attached an image with your indentation. It is wrong. Recheck and do it correctly =)

I also commented on your developer create action.. again.. fix it =)

![Screen shot 2013-03-29 at 7 12 10 PM](https://f.cloud.github.com/assets/1449989/318315/22b02df8-9894-11e2-8f36-a1885a34e3ed.png)

**Comment by Khloud-Khalid** [comment]
@adamggg , @zoheiry , @KareemAliRahman  please review code, documentation, and scenario

**Comment by Khloud-Khalid** [comment]
@adamggg , @zoheiry  please review code and documentation =)

**Comment by adamggg** [comment]
@Khloud-Khalid Check new comments in pull request =)

**Comment by Khloud-Khalid** [comment]
@adamggg done

**Comment by krmali** [comment]
check the comment

**Comment by Khloud-Khalid** [comment]
@adamggg , @KareemAliRahman done

**Comment by adamggg** [comment]
![Uploading Screen shot 2013-04-22 at 9.17.04 PM.png . . .]()

**Comment by adamggg** [comment]
![Screen shot 2013-04-22 at 9 17 04 PM](https://f.cloud.github.com/assets/1449989/411109/49a5b680-ab81-11e2-846c-a1fc30b331d5.png)

There is a problem with your routes! @Khloud-Khalid =D

**Comment by Khloud-Khalid** [comment]
@adamggg the route is developers/new

**Comment by adamggg** [comment]
Verified

**Comment by krmali** [comment]
Scenario verified.

**Comment by Khloud-Khalid** [comment]
@zoheiry please review the tests

**Comment by zoheiry** [comment]
1 failure:
  Expected response to be a redirect to <
http://test.host/ar/developers/my_subscriptions/choose_sub> but was a
redirect to http://test.host/?locale=ar

**Comment by Khloud-Khalid** [comment]
@zoheiry it's fixed now

**Comment by zoheiry** [comment]
0 failures, tests verifed
