### ISSUE TITLE
C1S7 - As a guest, I should be able to signup as a gamer

### ISSUE THREAD

**Issue by krmali** [MGhanem/smartsoft-13#86]
Success: Click on the signup button and i get redirected to to a 3 step signup form where in the first step i Enter my username, password, confirm password, Email, country, age, and education level, the second i am asked to connect to facebook, and the third step i am asked to connect to twitter, with option to skip the 2nd and 3rd step.
Failure: I'm already signed in, no signup button will appear, or i entered something invalid in step 1, the page loads again and i am redirected to step 1 and the fields where the errors occured are highlighted and the user is notified with the appropriate error.
Research on ruby on rails creating models
Tasks:
C1S7.0:Research on ruby on rails creating models
C1S7.1:Create sequence diagram @Khloud-Khalid 
C1S7.2:Making simple view 
C1S7.3:Implemeting sign up @adamggg 
C1S7.4:Handling invalid errors from the user
C1S7.5:Writing documentation @zoheiry

**Comment by m0hamed** [comment]
code-pending means that you have finished the code and are waiting for someone to review. please remove the code pending lable

**Comment by Khloud-Khalid** [comment]
returning arrows should be dashed
wrong module name devise*
error messages from the model gamer is the failure scenario, success not modeled in the UML

**Comment by krmali** [comment]
@Khloud-Khalid , regarding the UML:
1- The returning arrows are not dashed all the time, it is dashed only when the user is waiting for something from the UI , which is not the case here (the user is not waiting for error messages)
2- the module name <<MODULE>> is put because devise is modeled here as a closed box, I didn't implement the methods inside (Dr. Fatma said to model it like this)
3- Again the error messages between the <<MODEL>> Gamer and the <<MODULE>> Devise is not modeled in details as this all is abstracted by the Devise gem which I didn't implement (It is all inside the gem Devise).

**Comment by NourhanMohamed** [comment]
Close the issue ya gama3a talama merged
