### ISSUE TITLE
C1S9 - As a gamer, I should be able to SignOut

### ISSUE THREAD

**Issue by zoheiry** [MGhanem/smartsoft-13#87]
Success: Click on the Sign out button and i am redirected to the home page
Failure: Not Signed in, no sign out button will appear
Tasks:
1. Sequence Diagram @Khloud-Khalid 
2. Documentation @AmrARaouf 
3. Implementing action to handle failures and validations @KareemAliRahman @adamggg  
4. UI
5. Research how to check if user signed in or not

**Comment by krmali** [comment]
Coding style are fine.

**Comment by NourhanMohamed** [comment]
Close the issue ya gama3a talama merged
