### ISSUE TITLE
C4F6 - feature, Provide a list of reported keywords to the admin

### ISSUE THREAD

**Issue by omar-mohyeldin** [MGhanem/smartsoft-13#89]
success: takes no arguments and returns to the admin a list containing the keywords that are pending for approval in the database
failure: returns an empty list if no words are pending for approval
Tasks:
Research feature implementation using ruby
implememnt finding all unapproved keywords in database and returning a list of all of them @karimngr 
create feature's documentation @AmrARaouf 
create feature's UML diagram @Mirna-Yacout 

@m0hamed

**Comment by m0hamed** [comment]
This works for me :+1:

**Comment by ghost** [comment]
works for me

**Comment by m0hamed** [comment]
matyallah close ento mestaneyeen eh

**Comment by ghost** [comment]
reopened for sprint1

**Comment by ghost** [comment]
@Omar-Hossam  reopened to fix format and for scenario review

**Comment by ghost** [comment]
well this issue is good to go for this sprint now  will be closed

**Comment by nohahesham** [comment]
verified
