### ISSUE TITLE
C4.F04 - Function, record the approval of a certain keyword by the admin

### ISSUE THREAD

**Issue by Mirna-Yacout** [MGhanem/smartsoft-13#90]
success: Takes a keyword_id and returns true if it was approved.
failure: returns false in case the keyword doesn't exist in the database.

tasks:
0. Research
1. Documentation @AmrARaouf 
2. Sequence Diagram @Khloud-Khalid 
3. search and approve the synonym in the database @Omar-Hossam @karimngr

**Comment by m0hamed** [comment]
works for me :+1:
