### ISSUE TITLE
C1S10 - As a Gamer/Gamer(developer) should be able to change my account information

### ISSUE THREAD

**Issue by zoheiry** [MGhanem/smartsoft-13#91]
Success: Click on settings button, redirected to the update info page, where i can update my username, E-mail, password, country, age, and education level
Failure: Not Signed in no settings button will appear, or try to leave any of the fields empty, he will be redirected again to the same page and the field where the error occured will be highlighted and the error stated
Tasks:
1. Sequence Diagram @Khloud-Khalid 
2. Implementing UI  
3. Implement controller action handler @adamggg @KareemAliRahman 
4. Documentation @AmrARaouf 
5. Research how to use devise

**Comment by krmali** [comment]
Coding style are fine.

**Comment by NourhanMohamed** [comment]
Close the issue ya gama3a talama merged
