### ISSUE TITLE
C4S11 - As a developer, I can search for word in category

### ISSUE THREAD

**Issue by m0hamed** [MGhanem/smartsoft-13#92]
Success: if the word is tagged in this particular category, the developer will see the keyword and its corresponding synonyms
Failure: 
--> if the keyword not tagged in category but exists in database 
--> No Such keyword found in this category, But it exists in our database you can remove filters to view the keyword. if the keyword is not in category nor the database 
--> No such word exists, you can add this word to the database.  
Tasks: 
Sequence Diagram @nourhanZ 
Documentation @mostafahassaan 
Scenario @KareemAliRahman 
Implementation @NourhanMohamed

**Comment by NourhanMohamed** [comment]
Commented on lines in the pull request ;)

**Comment by nourhanZ** [comment]
1) please change the signature of the method to have first the parameter type:parameter name, ex string:name
2) please can you change the title of the sequence diagram to have the following format:
Diagram type Diagram name [(parameter type:parameter Name)] : [return value type] 
as this will make things easier later if we want to reference one of the diagrams in another diagram -- we can also keep the story number to make things easier.
3) why didn't you make the line going back from controller to view dotted

**Comment by mostafahassaan** [comment]
1) add author in all documentation 
2) check comments in search_controller

**Comment by m0hamed** [comment]
@nourhanZ The controller isnt returning something to the view it is rendering the view again

**Comment by m0hamed** [comment]
please review

**Comment by mostafahassaan** [comment]
@m0hamed zawed author yabo ashraf wenaby, homa etneen bas el feehom author

**Comment by nourhanZ** [comment]
1) I have no other comments but please separate the Parameter Type and Parameter Name with :

**Comment by m0hamed** [comment]
please review tany

**Comment by NourhanMohamed** [comment]
check the comments on the pull request :)

**Comment by m0hamed** [comment]
please review ya @NourhanMohamed

**Comment by NourhanMohamed** [comment]
verified bardo :+1:

**Comment by NourhanMohamed** [comment]
same goes here bardo, pull my branch 3ashan el changes ely ana 3amaltha 3ande :)

**Comment by mostafahassaan** [comment]
small issues with docs, check comments again

**Comment by NourhanMohamed** [comment]
verified :+1:

**Comment by mostafahassaan** [comment]
we ashraf rod 3ala el mobile

**Comment by m0hamed** [comment]
please review

**Comment by nourhanZ** [comment]
Verified

**Comment by m0hamed** [comment]
can someone please merge my pull request ;)

**Comment by NourhanMohamed** [comment]
Merged :D

**Comment by m0hamed** [comment]
ropened for sprint 1

**Comment by m0hamed** [comment]
please review

**Comment by nourhanZ** [comment]
The actor is still missing, please add it

**Comment by nourhanZ** [comment]
The arrow of the actor should indicate the action of the actor that causes this to happen not empty arrow 
changed it and tag me to review

**Comment by m0hamed** [comment]
models:
category.rb

controllers:
search.rb

routes.rb

please review

**Comment by NourhanMohamed** [comment]
comments on pull request

**Comment by m0hamed** [comment]
please review

**Comment by NourhanMohamed** [comment]
reviewed, comments on the pull request

**Comment by m0hamed** [comment]
please review

**Comment by NourhanMohamed** [comment]
reviewed and the comments are there on the pull request

**Comment by m0hamed** [comment]
please review

**Comment by NourhanMohamed** [comment]
check back on pull request

**Comment by nourhanZ** [comment]
Everything is fine except that you draw the return line before the line that call the method so please fix this :)

**Comment by mostafahassaan** [comment]
Check tests in spec/models/category_spec.rb. 5 fails present.

**Comment by m0hamed** [comment]
please review

**Comment by nourhanZ** [comment]
verified :)

**Comment by mostafahassaan** [comment]
verified

**Comment by NourhanMohamed** [comment]
code verified (Y)

**Comment by krmali** [comment]
Scenario verified

**Comment by NourhanMohamed** [comment]
code verified again

**Comment by krmali** [comment]
Scenario verified

**Comment by nourhanZ** [comment]
UML verified
