### ISSUE TITLE
C4.F1 - feature, Provide a list of words that a given user never voted on before

### ISSUE THREAD

**Issue by nourhanZ** [MGhanem/smartsoft-13#93]
Success:
Input is ID of a certain user(gamer), integer that represents numbers of keywords to be returned, integer to specify the language of keywords to be returned.
Output is a list of words that the user with the given ID never voted on before.

Failure:
If there is no keywords in the database with the specified language or if the user voted on all keywords in the database, an empty list will be returned.

Tasks:
C4.F1.1 - Research on the relations in rails and how to manage them
C4.F1.2 - Documentation @mostafahassaan 
C4.F1.3 - Sequence Diagram @Fattouh92 
C4.F1.4 - Implementation @NourhanMohamed  @m0hamed

**Comment by m0hamed** [comment]
I added comments on the lines in the pull request directly. please review them and correct

**Comment by NourhanMohamed** [comment]
I added some other comments on the pull request, too. 
Generally, numbers of characters per line should not exceed 80 characters, so please split long lines across shorter ones :checkered_flag:

**Comment by nourhanZ** [comment]
@Fattouh92  would you please re-open my UML as my code will be updated according to ashraf's & nourhan's comments so I will need to update the UML as well :)

**Comment by mostafahassaan** [comment]
Please check comments on docs

**Comment by nourhanZ** [comment]
@NourhanMohamed @m0hamed @mostafahassaan @Fattouh92  please review

**Comment by NourhanMohamed** [comment]
see comments on pull request

**Comment by nourhanZ** [comment]
@NourhanMohamed @m0hamed please review again

**Comment by NourhanMohamed** [comment]
check the comments once more

**Comment by mostafahassaan** [comment]
verified

**Comment by nourhanZ** [comment]
@NourhanMohamed @m0hamed review please:)

**Comment by NourhanMohamed** [comment]
check the comments

**Comment by nourhanZ** [comment]
@NourhanMohamed @m0hamed please review agaaain

**Comment by NourhanMohamed** [comment]
For me it's verified, @m0hamed please review and change the label if everything is fine

**Comment by nourhanZ** [comment]
@m0hamed please review agaaain as I added the method for both languages

**Comment by m0hamed** [comment]
verified

**Comment by nourhanZ** [comment]
:dancer: :dancers: :dancer:

**Comment by mostafahassaan** [comment]
merged :)

**Comment by nourhanZ** [comment]
@mostafahassaan @NourhanMohamed @m0hamed @Khloud-Khalid please review :)

**Comment by NourhanMohamed** [comment]
reviewed, check the pull request comments

**Comment by mostafahassaan** [comment]
use documentation convention
 # author:
  #   Mostafa Hassaan
  # description:
  #   function returns a hash with all keywords followed by a developer
  # params:
  #   gamer_id: id used to get the developer
  # success:
  #   returns a hash containing all keywords followed by the given developer
  # failure:
  #   returns empty hash if the developer doesn't follow any keywords

**Comment by m0hamed** [comment]
verified

**Comment by Khloud-Khalid** [comment]
verified

**Comment by nourhanZ** [comment]
@NourhanMohamed @mostafahassaan please review again :)

**Comment by NourhanMohamed** [comment]
check pull request comments

**Comment by mostafahassaan** [comment]
docs verified

**Comment by nourhanZ** [comment]
@NourhanMohamed please review again :)

**Comment by NourhanMohamed** [comment]
code verified

**Comment by NourhanMohamed** [comment]
I'm merging this now, so please close this issue @nourhanZ =)
