### ISSUE TITLE
C4S14 - As a Developer, I can add word to database

### ISSUE THREAD

**Issue by m0hamed** [MGhanem/smartsoft-13#94]
Success: Add new Keyword to the database.Suggest to follow keyword.
Failure: Keyword already exists. Admin may decide to limit certain subscriptions
Tasks:
Sequence Diagram @nourhanZ 
Documentation @mostafahassaan 
Senario @KareemAliRahman 
Implementation @NourhanMohamed

**Comment by NourhanMohamed** [comment]
Refer to the pull request for the comments regarding the code ;)

**Comment by nourhanZ** [comment]
1) please change the signature of the method to have first the parameter type:parameter name, ex string:name
2) the then part in the alt part is not labeled with the [condition of the if] so please add this 
3) reconsider the place of the [else] label please
4) why don't you add the optional parameters of method add_keyword_to_database to make the flow in the UML more clarified as you're using the is_english parameter later in the opt part
5) finally please can you change the title of the sequence diagram to have the following format:
    Diagram type Diagram name [(parameter type:parameter Name)] : [return value type] 
    as this will make things easier later if we want to reference one of the diagrams in another diagram -- we can also keep the story number to make things easier

**Comment by m0hamed** [comment]
please review ya 7elween

**Comment by nourhanZ** [comment]
1) please separate the Parameter Type and the Parameter Name with :
2) I still have the same comment that the UML doesn't show the source of is_english, I would prefer if you add this optional parameter to the method in UML
3) you name status in the loop in the UML while it's named success in the code so please give both the same name

**Comment by mostafahassaan** [comment]
check the pull request for comments

**Comment by m0hamed** [comment]
@nourhanZ about is_english it is not in the view so I am not sending it in the create however I added it to the call to add_keyword_to_database

**Comment by m0hamed** [comment]
everyone please review again

**Comment by NourhanMohamed** [comment]
check the comments on the pull request :)

**Comment by m0hamed** [comment]
please review ya @NourhanMohamed

**Comment by NourhanMohamed** [comment]
Verified :+1:

**Comment by m0hamed** [comment]
mabrooooooooooooooook, a5eeran. Mesh 3aref a2olek eh wallahi. ana sa3eed
gedan

**Comment by NourhanMohamed** [comment]
@m0hamed just pull my branch to correct those changes I did in my files :)

**Comment by mostafahassaan** [comment]
Ana maba2etsh 3aref anho functions beta3et anho branch, fee la5batah bent kalb 3andoko ento el etneen.
Anyway, just add author on top where the comment is we 5alas

**Comment by m0hamed** [comment]
please review again

**Comment by NourhanMohamed** [comment]
verified :+1:

**Comment by mostafahassaan** [comment]
mabrook :fireworks:

**Comment by nourhanZ** [comment]
verified

**Comment by NourhanMohamed** [comment]
@m0hamed howa ezay el pull request hena closed and merged by me wana m3mlteloosh close? 
3ashan kul el code ely hena already merged?

**Comment by m0hamed** [comment]
yes

**Comment by NourhanMohamed** [comment]
Nice :D

**Comment by m0hamed** [comment]
reopened for sprint 1

**Comment by m0hamed** [comment]
please review

**Comment by NourhanMohamed** [comment]
check the comments on the pull request

**Comment by nourhanZ** [comment]
I checked the pull request and the UML is not included in the files changed, did you change anything in the UML?!!
and if you changed something in the code that will require changing the UML, please do so and tag me in a comment after changing the UML to review the changes.

Thank you,

**Comment by mostafahassaan** [comment]
All docs should be with this template, check missing parts
 author:
      Amr Abdelraouf
 description:
     function description
 params:
     parameters
 success:
     success scenario
 failure:
     failure scenario

**Comment by m0hamed** [comment]
models/keyword.rb
models/category.rb
controllers/keywords_controller.rb
routes.rb

please review

**Comment by NourhanMohamed** [comment]
comments on pull request

**Comment by NourhanMohamed** [comment]
code  verified

**Comment by nourhanZ** [comment]
1) One of the return lines contain only one return value although you stated that the method return two things
and another one returns two values while the method only return one thing please fix this
2) The actor shouldn't have an activation box, only a time line so please fix this part :)

**Comment by m0hamed** [comment]
please review

**Comment by nourhanZ** [comment]
verified :)

**Comment by m0hamed** [comment]
please review

**Comment by NourhanMohamed** [comment]
check pull request comments, and a general comment that i'm gonna ask about is I don't think you can leave the test tags with your name

**Comment by m0hamed** [comment]
actually I left them on purpose to make the evaluation easier and so I make sure that all tests are passing. It also makes it very easy to see who is the owner of the test if it fails. you should do the same

**Comment by NourhanMohamed** [comment]
What u're saying makes sense but I should ask, just to make sure =)

**Comment by m0hamed** [comment]
please review again

**Comment by mostafahassaan** [comment]
docs verified

**Comment by NourhanMohamed** [comment]
code verified

**Comment by nourhanZ** [comment]
UML reopen, please fix the following points
1) The override used in the if condition is called override in the code but override category in the UML, please use same name for both.
2) why do you use brackets for categories in @keyword.categories = (categories_ in) in the UML. You didn't use brackets in the code so please try to fix this and the same thing in the other categories with brackets in the UML
3) call the keyword that returned from add_keyword_to_database @keyword to be consistent with the code 
4) The search view should have an activation box as we discussed 
5) remove the return line between view and the actor it's not needed

**Comment by m0hamed** [comment]
for number 2 i used brackets to show that this is a function call. it is implicit in ruby but ruby actually does a function call to a function called categories= and categories<< in the keyword model. these methods were created automatically by rails when we wrote has and belongs to many categores. I removed it either way

**Comment by m0hamed** [comment]
@KareemAliRahman please review

**Comment by mostafahassaan** [comment]
Are these tests yours?
rspec ./spec/models/keyword_spec.rb:137 # Keyword should return an empty list when searching for an unapproved keyword
rspec ./spec/models/keyword_spec.rb:204 # Keyword should return an empty list if keyword is unapproved
rspec ./spec/models/keyword_spec.rb:196 # Keyword should return an empty list if synonyms are unapproved

**Comment by krmali** [comment]
@m0hamed , check the comment on pull request.

**Comment by m0hamed** [comment]
@mostafahassaan no. my tests are tagged with my name. you can run all my tests by running

```
rspec --tag mohamed
```

**Comment by m0hamed** [comment]
@KareemAliRahman you should comment on the issue rather than the pull request since you are a scenario reviewer. also I dont understand what you mean. Could you please give me a scenario that you tried and didnt like the output of

**Comment by krmali** [comment]
@m0hamed , I searched for word that doesn't exist and added it and when I try to search for it again the word didn't appear in search, then I tried to add it again , it told me that the keywords is database.

**Comment by m0hamed** [comment]
@KareemAliRahman change the labels to senario reopen if it should be changed. I fixed it can you please review again.

@mostafahassaan could you please review again

**Comment by krmali** [comment]
the scenario issue is fixed now , scenario verified.

**Comment by mostafahassaan** [comment]
tests verified.

**Comment by m0hamed** [comment]
@nourhanZ please review

**Comment by nourhanZ** [comment]
Everything is fine except that there's a dashed line in the UML that seems to have no use please remove it and I will verify it :)

**Comment by m0hamed** [comment]
which line exactly. can you be more specific

**Comment by m0hamed** [comment]
@nourhanZ done please review

**Comment by m0hamed** [comment]
@nourhanZ please review the umls again

**Comment by m0hamed** [comment]
@nourhanZ can you please review my umls. we need this in master

**Comment by nourhanZ** [comment]
I will merge it now

**Comment by nourhanZ** [comment]
@m0hamed  as I mentioned in the pull request please fix conflicts then tag me to merge it

**Comment by nourhanZ** [comment]
UML verified please fix conflicts with master and I will merge

**Comment by nourhanZ** [comment]
I merged the story please close the pull request
