### ISSUE TITLE
C3.F1-As a Developer,I Should give developer word search, follow words and view visual stats permissions

### ISSUE THREAD

**Issue by nohahesham** [MGhanem/smartsoft-13#95]
Success:The user ID is given. I have to check the subscription model of the user. If the number of words didn't exceed the maximum then the permission is given, else the permission is denied for either the word search or follow words. For the visual stats, if the developer's model is free trial, permission is denied.
Failure:Developer ID is not found in the database.
Tasks:
1-Research
2-Documentation @SalmaFG 
3-UML @Fattouh92 
4-Match the given user id with the user id in the database and finding the remaining words and accordingly giving the permissions
5-Implementing function @Omar-Hossam   @m0hamed

**Comment by m0hamed** [comment]
I added coments to your pull request directly please review them

**Comment by NourhanMohamed** [comment]
Remove the Status-inProgress label please
N.B I still didn't review the code

**Comment by NourhanMohamed** [comment]
According to code conventions, variable names should be lower-case ASCII letters separated by underscore. 
Example: projectName should be replaced by project_name instead
please use proper indentation, like when you have an if statement, the lines following the condition should be indented by 2 spaces, and the end of the if statement should be aligned on the same line as the if
Be sure all lines are at most 80 characters long, and split long lines among multiple shorter ones
I added some comments on the pull request itself, please check them out and correct them, too :)

**Comment by nohahesham** [comment]
plz review again
@m0hamed
@NourhanMohamed 
@SalmaFG 
@Fattouh92

**Comment by NourhanMohamed** [comment]
please delete the un-necessary UML files, just keep the final version and re-push your work
I'm reviewing the code and i'll leave comments over the pull request

**Comment by m0hamed** [comment]
please tag a pull request with this issue number

**Comment by NourhanMohamed** [comment]
Another thing, we agreed that we'll use a single method to represent the 3 permission getters
You didn't abide by this, and this is too much redundant code so please merge the 3 methods in one
@m0hamed I'm done reviewing please re-review me if I forgot something

**Comment by nohahesham** [comment]
@m0hamed 
@NourhanMohamed 
plz review

**Comment by m0hamed** [comment]
noha please change the lables on the issue if you want people to review
your code.

**Comment by m0hamed** [comment]
Where is your pull request

**Comment by m0hamed** [comment]
please delete the wrong umls

**Comment by NourhanMohamed** [comment]
Delete the unncessary UML files, and merge the 3 methods in one as I mentioned before, and please apply the comments on all similar cases mesh lazem aktebhom 3ala case case

**Comment by nohahesham** [comment]
@NourhanMohamed  ana knt sa2alt adam yest about en kol method lwa7daha 2al ok i dint know how to merge them now

**Comment by nohahesham** [comment]
@m0hamed i already deleted them

**Comment by m0hamed** [comment]
ok leave every method alone however for deletion you need to do
git rm <path/to/file>

**Comment by nohahesham** [comment]
@NourhanMohamed 
@m0hamed i did that for every uml i delete 
@Fattouh92

**Comment by m0hamed** [comment]
move the migration to a separate branch and for reviewing and delete the index view

**Comment by nohahesham** [comment]
what migration?? @m0hamed

**Comment by m0hamed** [comment]
arability/db/migrate/20130326160511_add_limits_to_subscription_model.rb

read the entire pull request and you will see it.

**Comment by nohahesham** [comment]
@m0hamed 
@NourhanMohamed 
@Fattouh92  pllz review

**Comment by nohahesham** [comment]
@Fattouh92

**Comment by NourhanMohamed** [comment]
@nohahesham check out the comments

**Comment by nohahesham** [comment]
@NourhanMohamed 
@m0hamed

**Comment by NourhanMohamed** [comment]
@m0hamed I'm done, w8 for a minute @nohahesham is pushing changed and review

**Comment by m0hamed** [comment]
you are done ezzay ya3ney

**Comment by NourhanMohamed** [comment]
I'm not done .. lel asaf :cry:

**Comment by NourhanMohamed** [comment]
Fe  arability/app/views/projects/index.html.erb line9 atwal men 80 characters
el types ely f method give_permissions lazem yb2o constants 
we need 3 getters for constants 3ashan yb2o accessible men barra
give_permission should be renamed to something descriptive like has_permission or get_permission
@m0hamed any other comments?

**Comment by nohahesham** [comment]
ana mesh fahma eh el getters de @NourhanMohamed

**Comment by nohahesham** [comment]
mmken asebha keda for now?

**Comment by nohahesham** [comment]
i will pull the master

**Comment by NourhanMohamed** [comment]
I can't merge you the code if it's not complete.. Ana ely hathaza2 mesh enty
w lazem ashraf kaman y review mynf3sh ana lwa7de
benesba lel getters wel constants nourhan zakaria kanet 3amlahom f one of her classes "vote.rb" you can check them out

**Comment by nohahesham** [comment]
how shall i get her class
a pull el master?

**Comment by NourhanMohamed** [comment]
Yes pull the master
Sent from my BlackBerry® from Vodafone

-----Original Message-----

**Comment by nohahesham** [comment]
@NourhanMohamed 
@m0hamed 
done

**Comment by NourhanMohamed** [comment]
@nohahesham I guess you should tag @Omar-Hossam as your code reviewer instead since they changed the reviewers cycle :)

**Comment by m0hamed** [comment]
since my subscription belongs to developer all methods should not be self. and should use the developer id of the developer belonging to the mysubscription model.

**Comment by nohahesham** [comment]
@m0hamed 
@SalmaFG

**Comment by m0hamed** [comment]
check the pull request for comments

**Comment by nohahesham** [comment]
@m0hamed

**Comment by m0hamed** [comment]
please check the pull request for comments

**Comment by m0hamed** [comment]
verified

**Comment by nohahesham** [comment]
@Omar-Hossam

**Comment by nohahesham** [comment]
@Omar-Hossam

**Comment by abulazm22** [comment]
verified

**Comment by AmrARaouf** [comment]
closed by mistake
