### ISSUE TITLE
C4.F2 - feature, Record votes dedicated to a given synonym

### ISSUE THREAD

**Issue by nourhanZ** [MGhanem/smartsoft-13#96]
Success: 
Input is an ID representing the gamer id and another ID representing the synonym id.
Output is boolean -- this method returns true if the vote has been recorded.

Failure:
returns false if the gamer already voted on the keyword this synonym belongs to before.

Tasks:
C4.F2.1 - Research
C4.F2.2 - Documentation @mostafahassaan 
C4.F2.3 - Sequence Diagram @Fattouh92 
C4.F2.4 - Implementation @NourhanMohamed @m0hamed

**Comment by m0hamed** [comment]
please donot use instance variables (those starting with @) unless required. also please use class << self rather than self. to create class methods.
here is a link explaining how to use class << self
http://www.railstips.org/blog/archives/2009/05/11/class-and-instance-methods-in-ruby/

**Comment by NourhanMohamed** [comment]
extending Ashraf's comments, See the comments on the pull request. Don't forget to split lines longer than 80 characters on multiple lines

**Comment by nourhanZ** [comment]
@Fattouh92  would you please re-open my UML as my code will be updated according to ashraf's & nourhan's comments so I will need to update the UML as well :)

**Comment by mostafahassaan** [comment]
please check the comments on docs :)

**Comment by nourhanZ** [comment]
@NourhanMohamed @m0hamed @mostafahassaan @Fattouh92 please review :)

**Comment by nourhanZ** [comment]
@NourhanMohamed @m0hamed please review code again

**Comment by m0hamed** [comment]
verified

**Comment by nourhanZ** [comment]
@NourhanMohamed @m0hamed

**Comment by NourhanMohamed** [comment]
verified
@m0hamed please review after me and change the label

**Comment by m0hamed** [comment]
verified I am closing the issue and merging the pull request

**Comment by m0hamed** [comment]
fix merge conflicts

**Comment by m0hamed** [comment]
@nourhanZ

**Comment by nourhanZ** [comment]
@m0hamed, @NourhanMohamed , @mostafahassaan  I fixed merge conflicts, merge please :)

**Comment by m0hamed** [comment]
ma3lesh lessah feeh errors

**Comment by nourhanZ** [comment]
@m0hamed please merge after checking class keyword :)

**Comment by m0hamed** [comment]
mabrook
